// Code generated by protoreg. DO NOT EDIT.
package test

import (
	"github.com/Nocccer/protoreg/test/sub"
)

func (m Struct1) Marshal() ([]uint16, error) {
	buf := make([]uint16, 19)
	// Field1
	for i := 0; i < len(m.Field1); i++ {
		if i >= 8 {break}
		buf[0+i] = uint16(m.Field1[i])
	}
	// Field2
	buf[8] = uint16(m.Field2)
	// Field3
	buf[9] = uint16(m.Field3)
	// Field4
	buf[10] = m.Field4
	// Field5
	length := len(m.Field5)
	if length % 2 != 0 { length += 1 }
	bytes := make([]byte, length)
	copy(bytes, m.Field5)
	for i := 0; i < length; i+=2 {
		if i >= 16 {break}
		buf[11+i/2] = uint16(bytes[i+1]) | uint16(bytes[i])<<8
	}
	// Field6
	buf[15] = uint16(m.Field6)

	return buf, nil
}

func (m *Struct1) Unmarshal(buf []uint16) error {
	var bytes []byte
	// Field1
	bytes = make([]byte, 8)
	for i, v := range buf[0:8] {
		if v == 0 {bytes = bytes[:i];break} // stop on empty char
		bytes[i] = byte(v)
	}
	m.Field1 = string(bytes)
	// Field2
	m.Field2 = int16(buf[8])
	// Field3
	m.Field3 = CustomUint16(buf[9])
	// Field4
	m.Field4 = buf[10]
	// Field5
	bytes = make([]byte, 8)
	for i, v := range buf[11:19] {
		low := byte(v >> 8)
		if low == 0 {bytes = bytes[:i*2];break} // stop on empty char
		bytes[i*2] = low
		high := byte(v)
		if high == 0 {bytes = bytes[:i*2+1];break} // stop on empty char
		bytes[i*2+1] = high
	}
	m.Field5 = string(bytes)
	// Field6
	m.Field6 = sub.CustomInt16(int16(buf[15]))

	return nil
}

