package generator

import (
	"fmt"
	"go/ast"
	"go/types"
	"log/slog"
	"os"
	"slices"
	"strings"

	"golang.org/x/tools/go/packages"
)

type ProtoRegGen struct {
	types             []string
	dir               string
	pkg               string
	log               *slog.Logger
	imports           []string
	content           string
	encoding          Encoding
	wordOrder         WordOrder
	tagKey            string
	mode              GenMode
	marshalFuncName   string
	unmarshalFuncName string
}

func NewGenerator(
	types []string,
	dir string,
	log *slog.Logger,
	opts ...func(*ProtoRegGen),
) *ProtoRegGen {
	g := &ProtoRegGen{
		types:             types,
		dir:               dir,
		log:               log,
		encoding:          BigEndian,
		wordOrder:         HighWordFirst,
		tagKey:            "protoreg",
		mode:              GenModeAll,
		marshalFuncName:   "Marshal",
		unmarshalFuncName: "Unmarshal",
	}

	for _, opt := range opts {
		opt(g)
	}

	return g
}

func WithTagKey(tagKey string) func(*ProtoRegGen) {
	return func(g *ProtoRegGen) {
		g.tagKey = tagKey
	}
}

func (g *ProtoRegGen) Generate() error {
	pkgs, err := g.loadPackage()
	if err != nil {
		return err
	}

	for _, p := range pkgs {
		g.pkg = p.Name
		for _, s := range p.Syntax {
			for _, decl := range s.Decls {
				genDecl, ok := decl.(*ast.GenDecl)
				if !ok {
					continue
				}

				for _, spec := range genDecl.Specs {
					typeSpec, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}

					if !slices.Contains(g.types, typeSpec.Name.Name) {
						continue
					}

					g.types = slices.DeleteFunc(g.types, func(s string) bool {
						return s == typeSpec.Name.Name
					})

					structType, ok := typeSpec.Type.(*ast.StructType)
					if !ok {
						continue
					}

					res, err := g.genFromStruct(
						typeSpec.Name.Name,
						*structType,
						p.TypesInfo,
					)
					if err != nil {
						return err
					}

					g.content += res.Code
				}
			}
		}
	}

	if len(g.types) != 0 {
		return fmt.Errorf(
			"not all types were processed. Remaining: %s",
			strings.Join(g.types, ", "),
		)
	}

	return nil
}

func (g *ProtoRegGen) Imports() string {
	var sb strings.Builder

	g.imports = slices.DeleteFunc(g.imports, func(s string) bool {
		return s == ""
	})

	if len(g.imports) == 0 {
		return sb.String()
	}

	sb.WriteString("import (\n")
	std, thirdparty := splitFunc(g.imports, func(i string) bool {
		return !strings.Contains(i, "github")
	})

	slices.Sort(std)
	std = slices.Compact(std)

	slices.Sort(thirdparty)
	thirdparty = slices.Compact(thirdparty)

	for _, imp := range std {
		fmt.Fprintf(&sb, "\t\"%s\"\n", imp)
	}
	sb.WriteString("\n")
	for _, imp := range thirdparty {
		fmt.Fprintf(&sb, "\t\"%s\"\n", imp)
	}
	sb.WriteString(")\n\n")

	return sb.String()
}

func (g *ProtoRegGen) WriteToFile(filename string) error {
	//nolint: gosec
	f, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer f.Close()

	// write comment about auto generated
	_, err = f.WriteString("// Code generated by protoreg. DO NOT EDIT.\n")
	if err != nil {
		return err
	}

	// Write package declaration
	_, err = fmt.Fprintf(f, "package %s\n\n", g.pkg)
	if err != nil {
		return err
	}

	// write imports
	_, err = f.WriteString(g.Imports())
	if err != nil {
		return err
	}

	_, err = f.WriteString(g.content)
	return err
}

func (g *ProtoRegGen) loadPackage() ([]*packages.Package, error) {
	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedSyntax | packages.NeedFiles | packages.NeedTypesInfo,
	}

	return packages.Load(cfg, g.dir)
}

type GenMode string

const (
	GenModeAll       GenMode = "all"
	GenModeMarshal   GenMode = "marshal"
	GenModeUnmarshal GenMode = "unmarshal"
)

type StructResult struct {
	Code string
}

func (g *ProtoRegGen) genFromStruct(
	name string,
	typ ast.StructType,
	typesInfo *types.Info,
) (StructResult, error) {
	g.log.Debug(
		"Generate code for struct",
		slog.String("struct", name),
	)

	// Reset to defaults before processing this struct
	g.encoding = BigEndian
	g.wordOrder = HighWordFirst
	g.mode = GenModeAll
	g.marshalFuncName = "Marshal"
	g.unmarshalFuncName = "Unmarshal"

	structRes := StructResult{}
	length := 0
	gens := []Generator{}

	// extract encoding and wordorder from empty field
	idx := slices.IndexFunc(typ.Fields.List, func(field *ast.Field) bool {
		return field.Names[0].Name == "_"
	})
	if idx != -1 {
		tagStr, ok := extractTagByKey(typ.Fields.List[idx].Tag.Value, g.tagKey)
		if ok {
			if err := g.extractOpts(tagStr); err != nil {
				return StructResult{}, err
			}
		}
	}

	g.log.Debug(
		"extract options",
		slog.String("encoding", string(g.encoding)),
		slog.String("wordorder", string(g.wordOrder)),
		slog.String("mode", string(g.mode)),
		slog.String("marshalFuncName", g.marshalFuncName),
		slog.String("unmarshalFuncName", g.unmarshalFuncName),
	)

	for _, field := range typ.Fields.List {
		if field.Tag == nil || field.Names[0].Name == "_" {
			continue
		}

		tagStr, ok := extractTagByKey(field.Tag.Value, g.tagKey)
		if !ok {
			continue
		}

		res, err := g.extractField(field.Names[0].Name, field.Type, tagStr, typesInfo)
		if err != nil {
			return StructResult{}, err
		}
		for _, r := range res {
			gens = append(gens, r.Gen)
			if r.Len > length {
				length = r.Len
			}
		}
	}

	var sb strings.Builder
	if g.mode != GenModeUnmarshal {
		g.log.Debug("generate marshaler")

		fmt.Fprintf(&sb, "func (m %s) %s() ([]uint16, error) {\n", name, g.marshalFuncName)
		fmt.Fprintf(&sb, "\tbuf := make([]uint16, %d)\n", length)

		var sbFields strings.Builder
		for _, gen := range gens {
			sbFields.WriteString(gen.Marshaler())
		}

		// Check if we need to declare i variable
		if strings.Contains(sbFields.String(), "i =") {
			sb.WriteString("\tvar i int\n")
		}

		// Check if we need to declare tmp16 variable
		if strings.Contains(sbFields.String(), "tmp16 = ") {
			sb.WriteString("\tvar tmp16 uint16\n")
		}

		// Check if we need to declare tmp32 variable
		if strings.Contains(sbFields.String(), "tmp32 = ") {
			sb.WriteString("\tvar tmp32 uint32\n")
		}

		// Check if we need to declare tmp64 variable
		if strings.Contains(sbFields.String(), "tmp64 = ") {
			sb.WriteString("\tvar tmp64 uint64\n")
		}

		sb.WriteString(sbFields.String())

		sb.WriteString("\n\treturn buf, nil\n")
		sb.WriteString("}\n\n")
	}

	if g.mode != GenModeMarshal {
		g.log.Debug("generate unmarshaler")

		fmt.Fprintf(&sb, "func (m *%s) %s(buf []uint16) error {\n", name, g.unmarshalFuncName)

		var sbFields strings.Builder
		for _, gen := range gens {
			sbFields.WriteString(gen.Unmarshaler())
		}

		// Check if we need to declare the bytes slice
		if strings.Contains(sbFields.String(), "bytes =") {
			sb.WriteString("\tvar bytes []byte\n")
		}

		// Check if we need to declare the runes slice
		if strings.Contains(sbFields.String(), "runes =") {
			sb.WriteString("\tvar runes []rune\n")
		}

		// Check if we need to declare tmp16 variable
		if strings.Contains(sbFields.String(), "tmp16 = ") {
			sb.WriteString("\tvar tmp16 uint16\n")
		}

		// Check if we need to declare tmp32 variable
		if strings.Contains(sbFields.String(), "tmp32 = ") {
			sb.WriteString("\tvar tmp32 uint32\n")
		}

		// Check if we need to declare tmp64 variable
		if strings.Contains(sbFields.String(), "tmp64 = ") {
			sb.WriteString("\tvar tmp64 uint64\n")
		}

		sb.WriteString(sbFields.String())

		sb.WriteString("\n\treturn nil\n")
		sb.WriteString("}\n\n")
	}

	structRes.Code = sb.String()

	return structRes, nil
}

func (g *ProtoRegGen) extractField(
	name string,
	typ ast.Expr,
	tagStr string,
	typesInfo *types.Info,
) ([]NewGenResult, error) {
	var results []NewGenResult

	t, ok := typesInfo.Types[typ]
	if !ok {
		return results, fmt.Errorf("unknown type: %v", typ)
	}

	g.log.Debug(
		"extract field",
		slog.String("field", name),
		slog.Any("type", t.Type.String()),
		slog.Any("tags", tagStr),
	)

	tag, err := extractTags(tagStr)
	if err != nil {
		return results, fmt.Errorf("failed to extract tags for %s: %v", name, err)
	}

	array, isArray := t.Type.Underlying().(*types.Array)
	if isArray {
		t.Type = array.Elem()
	}

	underlyingStr := t.Type.Underlying().String()
	switch {
	case strings.Contains(underlyingStr, "int") || strings.Contains(underlyingStr, "byte"):
		if !isArray {
			gen, err := g.newIntegerGen(name, t.Type, tag)
			if err != nil {
				return results, err
			}
			results = append(results, gen)
			return results, nil
		}
		for i := range array.Len() {
			gen, err := g.newIntegerGen(fmt.Sprintf("%s[%d]", name, i), t.Type, tag.DeepCopy())
			if err != nil {
				return results, err
			}
			results = append(results, gen)
			*tag.Offset = gen.Len
		}
		return results, nil
	case strings.Contains(underlyingStr, "float"):
		if !isArray {
			gen, err := g.newFloatGen(name, t.Type, tag)
			if err != nil {
				return results, err
			}
			results = append(results, gen)
			return results, nil
		}
		for i := range array.Len() {
			gen, err := g.newFloatGen(fmt.Sprintf("%s[%d]", name, i), t.Type, tag.DeepCopy())
			if err != nil {
				return results, err
			}
			results = append(results, gen)
			*tag.Offset = gen.Len
		}
		return results, nil
	case underlyingStr == "string":
		if isArray {
			return results, fmt.Errorf("string arrays are not supported: %s", name)
		}
		gen, err := g.newStringGen(name, t.Type, tag)
		if err != nil {
			return results, err
		}
		results = append(results, gen)
		return results, nil
	case underlyingStr == "bool":
		if !isArray {
			gen, err := g.newBoolGen(name, t.Type, tag)
			if err != nil {
				return results, err
			}
			results = append(results, gen)
			return results, nil
		}
		for i := range array.Len() {
			gen, err := g.newBoolGen(fmt.Sprintf("%s[%d]", name, i), t.Type, tag.DeepCopy())
			if err != nil {
				return results, err
			}
			results = append(results, gen)
			*tag.Offset = gen.Len
		}
		return results, nil
	default:
		return results, fmt.Errorf(
			"unsupported underlying field type: %s",
			t.Type.Underlying().String(),
		)
	}
}

func (g *ProtoRegGen) extractOpts(tagStr string) error {
	// Extract encoding and word order from the tag string
	parts := strings.SplitSeq(tagStr, ",")
	for part := range parts {
		switch {
		case strings.HasPrefix(part, "encoding="):
			g.encoding = Encoding(strings.TrimPrefix(part, "encoding="))
		case strings.HasPrefix(part, "wordorder="):
			g.wordOrder = WordOrder(strings.TrimPrefix(part, "wordorder="))
		case strings.HasPrefix(part, "mode="):
			g.mode = GenMode(strings.TrimPrefix(part, "mode="))
		case strings.HasPrefix(part, "marshalfunc="):
			g.marshalFuncName = strings.TrimPrefix(part, "marshalfunc=")
		case strings.HasPrefix(part, "unmarshalfunc="):
			g.unmarshalFuncName = strings.TrimPrefix(part, "unmarshalfunc=")
		}
	}

	if g.encoding != BigEndian && g.encoding != LittleEndian {
		return fmt.Errorf("invalid encoding: %v", g.encoding)
	}
	if g.wordOrder != HighWordFirst && g.wordOrder != LowWordFirst {
		return fmt.Errorf("invalid word order: %v", g.wordOrder)
	}
	if g.mode != GenModeAll && g.mode != GenModeMarshal && g.mode != GenModeUnmarshal {
		return fmt.Errorf("invalid mode: %v", g.mode)
	}

	return nil
}
