package generator

import (
	"fmt"
	"go/ast"
	"go/types"
	"log/slog"
	"os"
	"slices"
	"strings"

	"golang.org/x/tools/go/packages"
)

type ProtoRegGen struct {
	types     []string
	dir       string
	pkg       string
	log       *slog.Logger
	imports   []string
	content   string
	encoding  Encoding
	wordOrder WordOrder
}

func NewGenerator(types []string, dir string, log *slog.Logger) *ProtoRegGen {
	return &ProtoRegGen{
		types:     types,
		dir:       dir,
		log:       log,
		encoding:  BigEndian,
		wordOrder: HighWordFirst,
	}
}

func (g *ProtoRegGen) Generate() error {
	pkgs, err := g.loadPackage()
	if err != nil {
		return err
	}

	for _, p := range pkgs {
		g.pkg = p.Name
		for _, s := range p.Syntax {
			for _, decl := range s.Decls {
				genDecl, ok := decl.(*ast.GenDecl)
				if !ok {
					continue
				}

				for _, spec := range genDecl.Specs {
					typeSpec, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}

					if !slices.Contains(g.types, typeSpec.Name.Name) {
						continue
					}

					g.types = slices.DeleteFunc(g.types, func(s string) bool {
						return s == typeSpec.Name.Name
					})

					structType, ok := typeSpec.Type.(*ast.StructType)
					if !ok {
						continue
					}

					res, err := g.genFromStruct(
						typeSpec.Name.Name,
						*structType,
						p.TypesInfo,
					)
					if err != nil {
						return err
					}

					g.content += res.Code
				}
			}
		}
	}

	if len(g.types) != 0 {
		return fmt.Errorf(
			"not all types were processed. Remaining: %s",
			strings.Join(g.types, ", "),
		)
	}

	return nil
}

func (g *ProtoRegGen) Imports() string {
	var sb strings.Builder

	g.imports = slices.DeleteFunc(g.imports, func(s string) bool {
		return s == ""
	})

	if len(g.imports) == 0 {
		return sb.String()
	}

	sb.WriteString("import (\n")
	g.imports = slices.Compact(g.imports)
	slices.Sort(g.imports)
	for _, imp := range g.imports {
		sb.WriteString(fmt.Sprintf("\t\"%s\"\n", imp))
	}
	sb.WriteString(")\n\n")

	return sb.String()
}

func (g *ProtoRegGen) WriteToFile(filename string) error {
	f, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer f.Close()

	// write comment about auto generated
	_, err = f.WriteString("// Code generated by protoreg. DO NOT EDIT.\n")
	if err != nil {
		return err
	}

	// Write package declaration
	_, err = f.WriteString(fmt.Sprintf("package %s\n\n", g.pkg))
	if err != nil {
		return err
	}

	// write imports
	_, err = f.WriteString(g.Imports())
	if err != nil {
		return err
	}

	_, err = f.WriteString(g.content)
	return err
}

func (g *ProtoRegGen) loadPackage() ([]*packages.Package, error) {
	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedSyntax | packages.NeedFiles | packages.NeedTypesInfo,
	}

	return packages.Load(cfg, g.dir)
}

type GenMode string

const (
	GenModeAll       GenMode = "all"
	GenModeMarshal   GenMode = "marshal"
	GenModeUnmarshal GenMode = "unmarshal"
)

type StructResult struct {
	Code string
}

func (g *ProtoRegGen) genFromStruct(
	name string,
	typ ast.StructType,
	typesInfo *types.Info,
) (StructResult, error) {
	g.log.Debug(
		"Generate code for struct",
		slog.String("struct", name),
	)

	structRes := StructResult{}
	gen := GenModeAll
	length := 0
	gens := []Generator{}

	// extract encoding and wordorder from empty field
	idx := slices.IndexFunc(typ.Fields.List, func(field *ast.Field) bool {
		return field.Names[0].Name == "_"
	})
	if idx != -1 {
		tagStr, ok := extractProtoRegTag(typ.Fields.List[idx].Tag.Value)
		if ok {
			if err := g.extractOpts(tagStr); err != nil {
				return StructResult{}, err
			}
		}
	}

	g.log.Debug(
		"extract options",
		slog.String("encoding", string(g.encoding)),
		slog.String("wordorder", string(g.wordOrder)),
	)

	for _, field := range typ.Fields.List {
		if field.Tag == nil || field.Names[0].Name == "_" {
			continue
		}

		tagStr, ok := extractProtoRegTag(field.Tag.Value)
		if !ok {
			continue
		}

		res, err := g.extractField(field.Names[0].Name, field.Type, tagStr, typesInfo)
		if err != nil {
			return StructResult{}, err
		}
		gens = append(gens, res.Gen)

		if res.Len > length {
			length = res.Len
		}
	}

	var sb strings.Builder
	if gen != GenModeUnmarshal {
		g.log.Debug("generate marshaler")

		sb.WriteString(fmt.Sprintf("func (m %s) Marshal() ([]uint16, error) {\n", name))
		sb.WriteString(fmt.Sprintf("\tbuf := make([]uint16, %d)\n", length))

		for _, gen := range gens {
			sb.WriteString(gen.Marshaler())
		}

		sb.WriteString("\n\treturn buf, nil\n")
		sb.WriteString("}\n\n")
	}

	if gen != GenModeMarshal {
		g.log.Debug("generate unmarshaler")

		sb.WriteString(fmt.Sprintf("func (m *%s) Unmarshal(buf []uint16) error {\n", name))

		var sbFields strings.Builder
		for _, gen := range gens {
			sbFields.WriteString(gen.Unmarshaler())
		}

		// Check if we need to declare the bytes slice
		if strings.Contains(sbFields.String(), "bytes =") {
			sb.WriteString("\tvar bytes []byte\n")
		}

		sb.WriteString(sbFields.String())

		sb.WriteString("\n\treturn nil\n")
		sb.WriteString("}\n\n")
	}

	structRes.Code = sb.String()

	return structRes, nil
}
