version: "2"

linters:
  default: standard
  enable:
    - lll 
    - sloglint
    - copyloopvar
    - gosec
    - tagalign
    - testifylint

  exclusions:
    rules:
      - linters:
          - errcheck
        source: "^.*defer.*$"
      

formatters:
  enable:
    - gofumpt
    - goimports
    - golines