// Code generated by protoreg. DO NOT EDIT.
package tests

import (
	"math"

	"github.com/Nocccer/protoreg/tests/extern"
)

func (m BigEndianHighWord) Marshal() ([]uint16, error) {
	buf := make([]uint16, 54)
	var i int
	var tmp16 uint16
	var tmp32 uint32
	var tmp64 uint64
	// Uint8Low
	buf[0] = buf[0] | uint16(m.Uint8Low)
	// Uint8High
	buf[0] = buf[0] | uint16(m.Uint8High) << 8
	// ByteLow
	buf[1] = buf[1] | uint16(m.ByteLow)
	// ByteHigh
	buf[1] = buf[1] | uint16(m.ByteHigh) << 8
	// Int8Low
	buf[2] = buf[2] | uint16(uint8(m.Int8Low))
	// Int8High
	buf[2] = buf[2] | uint16(uint8(m.Int8High)) << 8
	// Uint16
	buf[3] = m.Uint16
	// Int16
	buf[4] = uint16(m.Int16)
	// Uint32
	buf[6] = uint16(m.Uint32)
	buf[5] = uint16(m.Uint32 >> 16)
	// Int32
	buf[8] = uint16(m.Int32)
	buf[7] = uint16(m.Int32 >> 16)
	// Uint64
	buf[12] = uint16(m.Uint64)
	buf[11] = uint16(m.Uint64 >> 16)
	buf[10] = uint16(m.Uint64 >> 32)
	buf[9] = uint16(m.Uint64 >> 48)
	// Int64
	buf[16] = uint16(m.Int64)
	buf[15] = uint16(m.Int64 >> 16)
	buf[14] = uint16(m.Int64 >> 32)
	buf[13] = uint16(m.Int64 >> 48)
	// Float32
	tmp32 = math.Float32bits(float32(m.Float32))
	buf[18] = uint16(tmp32)
	buf[17] = uint16(tmp32 >> 16)
	// Float64
	tmp64 = math.Float64bits(float64(m.Float64))
	buf[24] = uint16(tmp64)
	buf[23] = uint16(tmp64 >> 16)
	buf[22] = uint16(tmp64 >> 32)
	buf[21] = uint16(tmp64 >> 48)
	// StringASCII8
	length := len(m.StringASCII8)
	for i := 0; i < length; i+=2 {
		if i >= 18 {break}
		b1 := m.StringASCII8[i]
		var b2 byte
		if i+1 < length {b2 = m.StringASCII8[i+1]}
		buf[25+i/2] = uint16(b1) | uint16(b2) <<8
	}
	// StringASCII16
	for i := 0; i < len(m.StringASCII16); i++ {
		if i >= 9 {break}
		buf[34+i] = uint16(m.StringASCII16[i])
	}
	// StringUTF816
	i = 0
	for _, r := range m.StringUTF816 {
		if i >= 9 {break}
		buf[43+i] = uint16(r)
		i++
	}
	// Bool
	tmp16 = 0; if m.Bool {tmp16 = 1}
	buf[52] |= tmp16 << 0
	// Bit1
	tmp16 = 0; if m.Bit1 {tmp16 = 1}
	buf[53] |= tmp16 << 1
	// Bit3
	tmp16 = 0; if m.Bit3 {tmp16 = 1}
	buf[53] |= tmp16 << 3
	// Bit14
	tmp16 = 0; if m.Bit14 {tmp16 = 1}
	buf[53] |= tmp16 << 14

	return buf, nil
}

func (m *BigEndianHighWord) Unmarshal(buf []uint16) error {
	var bytes []byte
	var runes []rune
	var tmp16 uint16
	var tmp32 uint32
	var tmp64 uint64
	// Uint8Low
	m.Uint8Low = uint8(buf[0])
	// Uint8High
	m.Uint8High = uint8(buf[0] >> 8)
	// ByteLow
	m.ByteLow = uint8(buf[1])
	// ByteHigh
	m.ByteHigh = uint8(buf[1] >> 8)
	// Int8Low
	m.Int8Low = int8(buf[2])
	// Int8High
	m.Int8High = int8(buf[2] >> 8)
	// Uint16
	m.Uint16 = buf[3]
	// Int16
	m.Int16 = int16(buf[4])
	// Uint32
	m.Uint32 = uint32(buf[6]) | uint32(buf[5]) << 16
	// Int32
	m.Int32 = int32(buf[8]) | int32(buf[7]) << 16
	// Uint64
	m.Uint64 = uint64(buf[12]) | uint64(buf[11]) << 16 | uint64(buf[10]) << 32 | uint64(buf[9]) << 48
	// Int64
	m.Int64 = int64(buf[16]) | int64(buf[15]) << 16 | int64(buf[14]) << 32 | int64(buf[13]) << 48
	// Float32
	tmp32 = uint32(buf[18]) | uint32(buf[17]) << 16
	m.Float32 = math.Float32frombits(tmp32)
	// Float64
	tmp64 = uint64(buf[24]) | uint64(buf[23]) << 16 | uint64(buf[22]) << 32 | uint64(buf[21]) << 48
	m.Float64 = math.Float64frombits(tmp64)
	// StringASCII8
	bytes = make([]byte, 18)
	for i, v := range buf[25:34] {
		low := byte(v)
		if low == 0 {bytes = bytes[:i*2];break} // stop on empty char
		bytes[i*2] = low
		high := byte(v >> 8)
		if high == 0 {bytes = bytes[:i*2+1];break} // stop on empty char
		bytes[i*2+1] = high
	}
	m.StringASCII8 = string(bytes)
	// StringASCII16
	bytes = make([]byte, 9)
	for i, v := range buf[34:43] {
		if v == 0 {bytes = bytes[:i];break} // stop on empty char
		bytes[i] = byte(v)
	}
	m.StringASCII16 = string(bytes)
	// StringUTF816
	runes = make([]rune, 9)
	for i, v := range buf[43:52] {
		if v == 0 {runes = runes[:i];break} // stop on empty char
		runes[i] = rune(v)
	}
	m.StringUTF816 = string(runes)
	// Bool
	tmp16 = buf[52] & 0x0001
	if tmp16 != 0 { m.Bool = true } else { m.Bool = false }
	// Bit1
	tmp16 = buf[53] & 0x0002
	if tmp16 != 0 { m.Bit1 = true } else { m.Bit1 = false }
	// Bit3
	tmp16 = buf[53] & 0x0008
	if tmp16 != 0 { m.Bit3 = true } else { m.Bit3 = false }
	// Bit14
	tmp16 = buf[53] & 0x4000
	if tmp16 != 0 { m.Bit14 = true } else { m.Bit14 = false }

	return nil
}

func (m BigEndianHighWordAllCustom) Marshal() ([]uint16, error) {
	buf := make([]uint16, 54)
	var i int
	var tmp16 uint16
	var tmp32 uint32
	var tmp64 uint64
	// Uint8Low
	buf[0] = buf[0] | uint16(m.Uint8Low)
	// Uint8High
	buf[0] = buf[0] | uint16(m.Uint8High) << 8
	// ByteLow
	buf[1] = buf[1] | uint16(m.ByteLow)
	// ByteHigh
	buf[1] = buf[1] | uint16(m.ByteHigh) << 8
	// Int8Low
	buf[2] = buf[2] | uint16(uint8(m.Int8Low))
	// Int8High
	buf[2] = buf[2] | uint16(uint8(m.Int8High)) << 8
	// Uint16
	buf[3] = uint16(m.Uint16)
	// Int16
	buf[4] = uint16(m.Int16)
	// Uint32
	buf[6] = uint16(m.Uint32)
	buf[5] = uint16(m.Uint32 >> 16)
	// Int32
	buf[8] = uint16(m.Int32)
	buf[7] = uint16(m.Int32 >> 16)
	// Uint64
	buf[12] = uint16(m.Uint64)
	buf[11] = uint16(m.Uint64 >> 16)
	buf[10] = uint16(m.Uint64 >> 32)
	buf[9] = uint16(m.Uint64 >> 48)
	// Int64
	buf[16] = uint16(m.Int64)
	buf[15] = uint16(m.Int64 >> 16)
	buf[14] = uint16(m.Int64 >> 32)
	buf[13] = uint16(m.Int64 >> 48)
	// Float32
	tmp32 = math.Float32bits(float32(m.Float32))
	buf[18] = uint16(tmp32)
	buf[17] = uint16(tmp32 >> 16)
	// Float64
	tmp64 = math.Float64bits(float64(m.Float64))
	buf[24] = uint16(tmp64)
	buf[23] = uint16(tmp64 >> 16)
	buf[22] = uint16(tmp64 >> 32)
	buf[21] = uint16(tmp64 >> 48)
	// StringASCII8
	length := len(m.StringASCII8)
	for i := 0; i < length; i+=2 {
		if i >= 18 {break}
		b1 := m.StringASCII8[i]
		var b2 byte
		if i+1 < length {b2 = m.StringASCII8[i+1]}
		buf[25+i/2] = uint16(b1) | uint16(b2) <<8
	}
	// StringASCII16
	for i := 0; i < len(m.StringASCII16); i++ {
		if i >= 9 {break}
		buf[34+i] = uint16(m.StringASCII16[i])
	}
	// StringUTF816
	i = 0
	for _, r := range m.StringUTF816 {
		if i >= 9 {break}
		buf[43+i] = uint16(r)
		i++
	}
	// Bool
	tmp16 = 0; if m.Bool {tmp16 = 1}
	buf[52] |= tmp16 << 0
	// Bit1
	tmp16 = 0; if m.Bit1 {tmp16 = 1}
	buf[53] |= tmp16 << 1
	// Bit3
	tmp16 = 0; if m.Bit3 {tmp16 = 1}
	buf[53] |= tmp16 << 3
	// Bit14
	tmp16 = 0; if m.Bit14 {tmp16 = 1}
	buf[53] |= tmp16 << 14

	return buf, nil
}

func (m *BigEndianHighWordAllCustom) Unmarshal(buf []uint16) error {
	var bytes []byte
	var runes []rune
	var tmp16 uint16
	var tmp32 uint32
	var tmp64 uint64
	// Uint8Low
	m.Uint8Low = CustomUint8(buf[0])
	// Uint8High
	m.Uint8High = CustomUint8(buf[0] >> 8)
	// ByteLow
	m.ByteLow = CustomByte(buf[1])
	// ByteHigh
	m.ByteHigh = CustomByte(buf[1] >> 8)
	// Int8Low
	m.Int8Low = CustomInt8(buf[2])
	// Int8High
	m.Int8High = CustomInt8(buf[2] >> 8)
	// Uint16
	m.Uint16 = CustomUint16(buf[3])
	// Int16
	m.Int16 = CustomInt16(int16(buf[4]))
	// Uint32
	m.Uint32 = CustomUint32(buf[6]) | CustomUint32(buf[5]) << 16
	// Int32
	m.Int32 = CustomInt32(int32(buf[8]) | int32(buf[7]) << 16)
	// Uint64
	m.Uint64 = CustomUint64(buf[12]) | CustomUint64(buf[11]) << 16 | CustomUint64(buf[10]) << 32 | CustomUint64(buf[9]) << 48
	// Int64
	m.Int64 = CustomInt64(int64(buf[16]) | int64(buf[15]) << 16 | int64(buf[14]) << 32 | int64(buf[13]) << 48)
	// Float32
	tmp32 = uint32(buf[18]) | uint32(buf[17]) << 16
	m.Float32 = CustomFloat32(math.Float32frombits(tmp32))
	// Float64
	tmp64 = uint64(buf[24]) | uint64(buf[23]) << 16 | uint64(buf[22]) << 32 | uint64(buf[21]) << 48
	m.Float64 = CustomFloat64(math.Float64frombits(tmp64))
	// StringASCII8
	bytes = make([]byte, 18)
	for i, v := range buf[25:34] {
		low := byte(v)
		if low == 0 {bytes = bytes[:i*2];break} // stop on empty char
		bytes[i*2] = low
		high := byte(v >> 8)
		if high == 0 {bytes = bytes[:i*2+1];break} // stop on empty char
		bytes[i*2+1] = high
	}
	m.StringASCII8 = CustomString(bytes)
	// StringASCII16
	bytes = make([]byte, 9)
	for i, v := range buf[34:43] {
		if v == 0 {bytes = bytes[:i];break} // stop on empty char
		bytes[i] = byte(v)
	}
	m.StringASCII16 = CustomString(bytes)
	// StringUTF816
	runes = make([]rune, 9)
	for i, v := range buf[43:52] {
		if v == 0 {runes = runes[:i];break} // stop on empty char
		runes[i] = rune(v)
	}
	m.StringUTF816 = CustomString(runes)
	// Bool
	tmp16 = buf[52] & 0x0001
	if tmp16 != 0 { m.Bool = true } else { m.Bool = false }
	// Bit1
	tmp16 = buf[53] & 0x0002
	if tmp16 != 0 { m.Bit1 = true } else { m.Bit1 = false }
	// Bit3
	tmp16 = buf[53] & 0x0008
	if tmp16 != 0 { m.Bit3 = true } else { m.Bit3 = false }
	// Bit14
	tmp16 = buf[53] & 0x4000
	if tmp16 != 0 { m.Bit14 = true } else { m.Bit14 = false }

	return nil
}

func (m BigEndianHighWordAllCustomExtern) Marshal() ([]uint16, error) {
	buf := make([]uint16, 54)
	var i int
	var tmp16 uint16
	var tmp32 uint32
	var tmp64 uint64
	// Uint8Low
	buf[0] = buf[0] | uint16(m.Uint8Low)
	// Uint8High
	buf[0] = buf[0] | uint16(m.Uint8High) << 8
	// ByteLow
	buf[1] = buf[1] | uint16(m.ByteLow)
	// ByteHigh
	buf[1] = buf[1] | uint16(m.ByteHigh) << 8
	// Int8Low
	buf[2] = buf[2] | uint16(uint8(m.Int8Low))
	// Int8High
	buf[2] = buf[2] | uint16(uint8(m.Int8High)) << 8
	// Uint16
	buf[3] = uint16(m.Uint16)
	// Int16
	buf[4] = uint16(m.Int16)
	// Uint32
	buf[6] = uint16(m.Uint32)
	buf[5] = uint16(m.Uint32 >> 16)
	// Int32
	buf[8] = uint16(m.Int32)
	buf[7] = uint16(m.Int32 >> 16)
	// Uint64
	buf[12] = uint16(m.Uint64)
	buf[11] = uint16(m.Uint64 >> 16)
	buf[10] = uint16(m.Uint64 >> 32)
	buf[9] = uint16(m.Uint64 >> 48)
	// Int64
	buf[16] = uint16(m.Int64)
	buf[15] = uint16(m.Int64 >> 16)
	buf[14] = uint16(m.Int64 >> 32)
	buf[13] = uint16(m.Int64 >> 48)
	// Float32
	tmp32 = math.Float32bits(float32(m.Float32))
	buf[18] = uint16(tmp32)
	buf[17] = uint16(tmp32 >> 16)
	// Float64
	tmp64 = math.Float64bits(float64(m.Float64))
	buf[24] = uint16(tmp64)
	buf[23] = uint16(tmp64 >> 16)
	buf[22] = uint16(tmp64 >> 32)
	buf[21] = uint16(tmp64 >> 48)
	// StringASCII8
	length := len(m.StringASCII8)
	for i := 0; i < length; i+=2 {
		if i >= 18 {break}
		b1 := m.StringASCII8[i]
		var b2 byte
		if i+1 < length {b2 = m.StringASCII8[i+1]}
		buf[25+i/2] = uint16(b1) | uint16(b2) <<8
	}
	// StringASCII16
	for i := 0; i < len(m.StringASCII16); i++ {
		if i >= 9 {break}
		buf[34+i] = uint16(m.StringASCII16[i])
	}
	// StringUTF816
	i = 0
	for _, r := range m.StringUTF816 {
		if i >= 9 {break}
		buf[43+i] = uint16(r)
		i++
	}
	// Bool
	tmp16 = 0; if m.Bool {tmp16 = 1}
	buf[52] |= tmp16 << 0
	// Bit1
	tmp16 = 0; if m.Bit1 {tmp16 = 1}
	buf[53] |= tmp16 << 1
	// Bit3
	tmp16 = 0; if m.Bit3 {tmp16 = 1}
	buf[53] |= tmp16 << 3
	// Bit14
	tmp16 = 0; if m.Bit14 {tmp16 = 1}
	buf[53] |= tmp16 << 14

	return buf, nil
}

func (m *BigEndianHighWordAllCustomExtern) Unmarshal(buf []uint16) error {
	var bytes []byte
	var runes []rune
	var tmp16 uint16
	var tmp32 uint32
	var tmp64 uint64
	// Uint8Low
	m.Uint8Low = extern.CustomUint8(buf[0])
	// Uint8High
	m.Uint8High = extern.CustomUint8(buf[0] >> 8)
	// ByteLow
	m.ByteLow = extern.CustomByte(buf[1])
	// ByteHigh
	m.ByteHigh = extern.CustomByte(buf[1] >> 8)
	// Int8Low
	m.Int8Low = extern.CustomInt8(buf[2])
	// Int8High
	m.Int8High = extern.CustomInt8(buf[2] >> 8)
	// Uint16
	m.Uint16 = extern.CustomUint16(buf[3])
	// Int16
	m.Int16 = extern.CustomInt16(int16(buf[4]))
	// Uint32
	m.Uint32 = extern.CustomUint32(buf[6]) | extern.CustomUint32(buf[5]) << 16
	// Int32
	m.Int32 = extern.CustomInt32(int32(buf[8]) | int32(buf[7]) << 16)
	// Uint64
	m.Uint64 = extern.CustomUint64(buf[12]) | extern.CustomUint64(buf[11]) << 16 | extern.CustomUint64(buf[10]) << 32 | extern.CustomUint64(buf[9]) << 48
	// Int64
	m.Int64 = extern.CustomInt64(int64(buf[16]) | int64(buf[15]) << 16 | int64(buf[14]) << 32 | int64(buf[13]) << 48)
	// Float32
	tmp32 = uint32(buf[18]) | uint32(buf[17]) << 16
	m.Float32 = extern.CustomFloat32(math.Float32frombits(tmp32))
	// Float64
	tmp64 = uint64(buf[24]) | uint64(buf[23]) << 16 | uint64(buf[22]) << 32 | uint64(buf[21]) << 48
	m.Float64 = extern.CustomFloat64(math.Float64frombits(tmp64))
	// StringASCII8
	bytes = make([]byte, 18)
	for i, v := range buf[25:34] {
		low := byte(v)
		if low == 0 {bytes = bytes[:i*2];break} // stop on empty char
		bytes[i*2] = low
		high := byte(v >> 8)
		if high == 0 {bytes = bytes[:i*2+1];break} // stop on empty char
		bytes[i*2+1] = high
	}
	m.StringASCII8 = extern.CustomString(bytes)
	// StringASCII16
	bytes = make([]byte, 9)
	for i, v := range buf[34:43] {
		if v == 0 {bytes = bytes[:i];break} // stop on empty char
		bytes[i] = byte(v)
	}
	m.StringASCII16 = extern.CustomString(bytes)
	// StringUTF816
	runes = make([]rune, 9)
	for i, v := range buf[43:52] {
		if v == 0 {runes = runes[:i];break} // stop on empty char
		runes[i] = rune(v)
	}
	m.StringUTF816 = extern.CustomString(runes)
	// Bool
	tmp16 = buf[52] & 0x0001
	if tmp16 != 0 { m.Bool = true } else { m.Bool = false }
	// Bit1
	tmp16 = buf[53] & 0x0002
	if tmp16 != 0 { m.Bit1 = true } else { m.Bit1 = false }
	// Bit3
	tmp16 = buf[53] & 0x0008
	if tmp16 != 0 { m.Bit3 = true } else { m.Bit3 = false }
	// Bit14
	tmp16 = buf[53] & 0x4000
	if tmp16 != 0 { m.Bit14 = true } else { m.Bit14 = false }

	return nil
}

