// Code generated by protoreg. DO NOT EDIT.
package tests

func (m OnlyMarshaler) Marshal() ([]uint16, error) {
	buf := make([]uint16, 1)
	// UInt16
	buf[0] = m.UInt16

	return buf, nil
}

func (m *OnlyUnmarshaler) Unmarshal(buf []uint16) error {
	// UInt16
	m.UInt16 = buf[0]

	return nil
}

func (m CustomFuncNames) CustomMarshal() ([]uint16, error) {
	buf := make([]uint16, 1)
	// UInt16
	buf[0] = m.UInt16

	return buf, nil
}

func (m *CustomFuncNames) CustomUnmarshal(buf []uint16) error {
	// UInt16
	m.UInt16 = buf[0]

	return nil
}

