// Code generated by protoreg. DO NOT EDIT.
package tests

func (m CustomStructKey) Marshal() ([]uint16, error) {
	buf := make([]uint16, 1)
	// UInt16
	buf[0] = m.UInt16

	return buf, nil
}

func (m *CustomStructKey) Unmarshal(buf []uint16) error {
	// UInt16
	m.UInt16 = buf[0]

	return nil
}

