// Code generated by protoreg. DO NOT EDIT.
package tests

import (
	"math"
	"math/bits"

	"github.com/Nocccer/protoreg/tests/extern"
)

func (m LittleEndianLowWord) Marshal() ([]uint16, error) {
	buf := make([]uint16, 52)
	var i int
	var tmp32 uint32
	var tmp64 uint64
	// Uint8Low
	buf[0] = buf[0] | uint16(m.Uint8Low)<<8
	// Uint8High
	buf[0] = buf[0] | uint16(m.Uint8High)
	// ByteLow
	buf[1] = buf[1] | uint16(m.ByteLow)<<8
	// ByteHigh
	buf[1] = buf[1] | uint16(m.ByteHigh)
	// Int8Low
	buf[2] = buf[2] | uint16(uint8(m.Int8Low))<<8
	// Int8High
	buf[2] = buf[2] | uint16(uint8(m.Int8High))
	// Uint16
	buf[3] = bits.ReverseBytes16(m.Uint16)
	// Int16
	buf[4] = bits.ReverseBytes16(uint16(m.Int16))
	// Uint32
	buf[5] = bits.ReverseBytes16(uint16(m.Uint32))
	buf[6] = bits.ReverseBytes16(uint16(m.Uint32>>16))
	// Int32
	buf[7] = bits.ReverseBytes16(uint16(m.Int32))
	buf[8] = bits.ReverseBytes16(uint16(m.Int32>>16))
	// Uint64
	buf[9] = bits.ReverseBytes16(uint16(m.Uint64))
	buf[10] = bits.ReverseBytes16(uint16(m.Uint64>>16))
	buf[11] = bits.ReverseBytes16(uint16(m.Uint64>>32))
	buf[12] = bits.ReverseBytes16(uint16(m.Uint64>>48))
	// Int64
	buf[13] = bits.ReverseBytes16(uint16(m.Int64))
	buf[14] = bits.ReverseBytes16(uint16(m.Int64>>16))
	buf[15] = bits.ReverseBytes16(uint16(m.Int64>>32))
	buf[16] = bits.ReverseBytes16(uint16(m.Int64>>48))
	// Float32
	tmp32 = math.Float32bits(float32(m.Float32))
	buf[17] = bits.ReverseBytes16(uint16(tmp32))
	buf[18] = bits.ReverseBytes16(uint16(tmp32>>16))
	// Float64
	tmp64 = math.Float64bits(float64(m.Float64))
	buf[21] = bits.ReverseBytes16(uint16(tmp64))
	buf[22] = bits.ReverseBytes16(uint16(tmp64>>16))
	buf[23] = bits.ReverseBytes16(uint16(tmp64>>32))
	buf[24] = bits.ReverseBytes16(uint16(tmp64>>48))
	// StringASCII8
	length := len(m.StringASCII8)
	for i := 0; i < length; i+=2 {
		if i >= 18 {break}
		b1 := m.StringASCII8[i]
		var b2 byte
		if i+1 < length {b2 = m.StringASCII8[i+1]}
		buf[25+i/2] = uint16(b1)<<8 | uint16(b2)
	}
	// StringASCII16
	for i := 0; i < len(m.StringASCII16); i++ {
		if i >= 9 {break}
		buf[34+i] = uint16(m.StringASCII16[i])<<8
	}
	// StringUTF816
	i = 0
	for _, r := range m.StringUTF816 {
		if i >= 9 {break}
		buf[43+i] = uint16(r>>8) | uint16(r<<8)
		i++
	}

	return buf, nil
}

func (m *LittleEndianLowWord) Unmarshal(buf []uint16) error {
	var bytes []byte
	var runes []rune
	var tmp32 uint32
	var tmp64 uint64
	// Uint8Low
	m.Uint8Low = uint8(buf[0]>>8)
	// Uint8High
	m.Uint8High = uint8(buf[0])
	// ByteLow
	m.ByteLow = uint8(buf[1]>>8)
	// ByteHigh
	m.ByteHigh = uint8(buf[1])
	// Int8Low
	m.Int8Low = int8(buf[2]>>8)
	// Int8High
	m.Int8High = int8(buf[2])
	// Uint16
	m.Uint16 = bits.ReverseBytes16(buf[3])
	// Int16
	m.Int16 = int16(bits.ReverseBytes16(buf[4]))
	// Uint32
	m.Uint32 = uint32(bits.ReverseBytes16(buf[5])) | uint32(bits.ReverseBytes16(buf[6])) << 16
	// Int32
	m.Int32 = int32(bits.ReverseBytes16(buf[7])) | int32(bits.ReverseBytes16(buf[8]))<<16
	// Uint64
	m.Uint64 = uint64(bits.ReverseBytes16(buf[9])) | uint64(bits.ReverseBytes16(buf[10])) << 16 | uint64(bits.ReverseBytes16(buf[11])) << 32 | uint64(bits.ReverseBytes16(buf[12])) << 48
	// Int64
	m.Int64 = int64(bits.ReverseBytes16(buf[13])) | int64(bits.ReverseBytes16(buf[14])) << 16 | int64(bits.ReverseBytes16(buf[15])) << 32 | int64(bits.ReverseBytes16(buf[16])) << 48
	// Float32
	tmp32 = uint32(bits.ReverseBytes16(buf[17])) | uint32(bits.ReverseBytes16(buf[18])) << 16
	m.Float32 = math.Float32frombits(tmp32)
	// Float64
	tmp64 = uint64(bits.ReverseBytes16(buf[21])) | uint64(bits.ReverseBytes16(buf[22])) << 16 | uint64(bits.ReverseBytes16(buf[23])) << 32 | uint64(bits.ReverseBytes16(buf[24])) << 48
	m.Float64 = math.Float64frombits(tmp64)
	// StringASCII8
	bytes = make([]byte, 18)
	for i, v := range buf[25:34] {
		low := byte(v>>8)
		if low == 0 {bytes = bytes[:i*2];break} // stop on empty char
		bytes[i*2] = low
		high := byte(v)
		if high == 0 {bytes = bytes[:i*2+1];break} // stop on empty char
		bytes[i*2+1] = high
	}
	m.StringASCII8 = string(bytes)
	// StringASCII16
	bytes = make([]byte, 9)
	for i, v := range buf[34:43] {
		if v == 0 {bytes = bytes[:i];break} // stop on empty char
		bytes[i] = byte(v>>8)
	}
	m.StringASCII16 = string(bytes)
	// StringUTF816
	runes = make([]rune, 9)
	for i, v := range buf[43:52] {
		if v == 0 {runes = runes[:i];break} // stop on empty char
		runes[i] = rune(v>>8) | rune(v<<8)
	}
	m.StringUTF816 = string(runes)

	return nil
}

func (m LittleEndianLowWordAllCustom) Marshal() ([]uint16, error) {
	buf := make([]uint16, 52)
	var i int
	var tmp32 uint32
	var tmp64 uint64
	// Uint8Low
	buf[0] = buf[0] | uint16(m.Uint8Low)<<8
	// Uint8High
	buf[0] = buf[0] | uint16(m.Uint8High)
	// ByteLow
	buf[1] = buf[1] | uint16(m.ByteLow)<<8
	// ByteHigh
	buf[1] = buf[1] | uint16(m.ByteHigh)
	// Int8Low
	buf[2] = buf[2] | uint16(uint8(m.Int8Low))<<8
	// Int8High
	buf[2] = buf[2] | uint16(uint8(m.Int8High))
	// Uint16
	buf[3] = bits.ReverseBytes16(uint16(m.Uint16))
	// Int16
	buf[4] = bits.ReverseBytes16(uint16(m.Int16))
	// Uint32
	buf[5] = bits.ReverseBytes16(uint16(m.Uint32))
	buf[6] = bits.ReverseBytes16(uint16(m.Uint32>>16))
	// Int32
	buf[7] = bits.ReverseBytes16(uint16(m.Int32))
	buf[8] = bits.ReverseBytes16(uint16(m.Int32>>16))
	// Uint64
	buf[9] = bits.ReverseBytes16(uint16(m.Uint64))
	buf[10] = bits.ReverseBytes16(uint16(m.Uint64>>16))
	buf[11] = bits.ReverseBytes16(uint16(m.Uint64>>32))
	buf[12] = bits.ReverseBytes16(uint16(m.Uint64>>48))
	// Int64
	buf[13] = bits.ReverseBytes16(uint16(m.Int64))
	buf[14] = bits.ReverseBytes16(uint16(m.Int64>>16))
	buf[15] = bits.ReverseBytes16(uint16(m.Int64>>32))
	buf[16] = bits.ReverseBytes16(uint16(m.Int64>>48))
	// Float32
	tmp32 = math.Float32bits(float32(m.Float32))
	buf[17] = bits.ReverseBytes16(uint16(tmp32))
	buf[18] = bits.ReverseBytes16(uint16(tmp32>>16))
	// Float64
	tmp64 = math.Float64bits(float64(m.Float64))
	buf[21] = bits.ReverseBytes16(uint16(tmp64))
	buf[22] = bits.ReverseBytes16(uint16(tmp64>>16))
	buf[23] = bits.ReverseBytes16(uint16(tmp64>>32))
	buf[24] = bits.ReverseBytes16(uint16(tmp64>>48))
	// StringASCII8
	length := len(m.StringASCII8)
	for i := 0; i < length; i+=2 {
		if i >= 18 {break}
		b1 := m.StringASCII8[i]
		var b2 byte
		if i+1 < length {b2 = m.StringASCII8[i+1]}
		buf[25+i/2] = uint16(b1)<<8 | uint16(b2)
	}
	// StringASCII16
	for i := 0; i < len(m.StringASCII16); i++ {
		if i >= 9 {break}
		buf[34+i] = uint16(m.StringASCII16[i])<<8
	}
	// StringUTF816
	i = 0
	for _, r := range m.StringUTF816 {
		if i >= 9 {break}
		buf[43+i] = uint16(r>>8) | uint16(r<<8)
		i++
	}

	return buf, nil
}

func (m *LittleEndianLowWordAllCustom) Unmarshal(buf []uint16) error {
	var bytes []byte
	var runes []rune
	var tmp32 uint32
	var tmp64 uint64
	// Uint8Low
	m.Uint8Low = CustomUint8(buf[0]>>8)
	// Uint8High
	m.Uint8High = CustomUint8(buf[0])
	// ByteLow
	m.ByteLow = CustomByte(buf[1]>>8)
	// ByteHigh
	m.ByteHigh = CustomByte(buf[1])
	// Int8Low
	m.Int8Low = CustomInt8(buf[2]>>8)
	// Int8High
	m.Int8High = CustomInt8(buf[2])
	// Uint16
	m.Uint16 = CustomUint16(bits.ReverseBytes16(buf[3]))
	// Int16
	m.Int16 = CustomInt16(bits.ReverseBytes16(buf[4]))
	// Uint32
	m.Uint32 = CustomUint32(bits.ReverseBytes16(buf[5])) | CustomUint32(bits.ReverseBytes16(buf[6])) << 16
	// Int32
	m.Int32 = CustomInt32(int32(bits.ReverseBytes16(buf[7])) | int32(bits.ReverseBytes16(buf[8]))<<16)
	// Uint64
	m.Uint64 = CustomUint64(bits.ReverseBytes16(buf[9])) | CustomUint64(bits.ReverseBytes16(buf[10])) << 16 | CustomUint64(bits.ReverseBytes16(buf[11])) << 32 | CustomUint64(bits.ReverseBytes16(buf[12])) << 48
	// Int64
	m.Int64 = CustomInt64(int64(bits.ReverseBytes16(buf[13])) | int64(bits.ReverseBytes16(buf[14])) << 16 | int64(bits.ReverseBytes16(buf[15])) << 32 | int64(bits.ReverseBytes16(buf[16])) << 48)
	// Float32
	tmp32 = uint32(bits.ReverseBytes16(buf[17])) | uint32(bits.ReverseBytes16(buf[18])) << 16
	m.Float32 = CustomFloat32(math.Float32frombits(tmp32))
	// Float64
	tmp64 = uint64(bits.ReverseBytes16(buf[21])) | uint64(bits.ReverseBytes16(buf[22])) << 16 | uint64(bits.ReverseBytes16(buf[23])) << 32 | uint64(bits.ReverseBytes16(buf[24])) << 48
	m.Float64 = CustomFloat64(math.Float64frombits(tmp64))
	// StringASCII8
	bytes = make([]byte, 18)
	for i, v := range buf[25:34] {
		low := byte(v>>8)
		if low == 0 {bytes = bytes[:i*2];break} // stop on empty char
		bytes[i*2] = low
		high := byte(v)
		if high == 0 {bytes = bytes[:i*2+1];break} // stop on empty char
		bytes[i*2+1] = high
	}
	m.StringASCII8 = CustomString(bytes)
	// StringASCII16
	bytes = make([]byte, 9)
	for i, v := range buf[34:43] {
		if v == 0 {bytes = bytes[:i];break} // stop on empty char
		bytes[i] = byte(v>>8)
	}
	m.StringASCII16 = CustomString(bytes)
	// StringUTF816
	runes = make([]rune, 9)
	for i, v := range buf[43:52] {
		if v == 0 {runes = runes[:i];break} // stop on empty char
		runes[i] = rune(v>>8) | rune(v<<8)
	}
	m.StringUTF816 = CustomString(runes)

	return nil
}

func (m LittleEndianLowWordAllCustomExtern) Marshal() ([]uint16, error) {
	buf := make([]uint16, 52)
	var i int
	var tmp32 uint32
	var tmp64 uint64
	// Uint8Low
	buf[0] = buf[0] | uint16(m.Uint8Low)<<8
	// Uint8High
	buf[0] = buf[0] | uint16(m.Uint8High)
	// ByteLow
	buf[1] = buf[1] | uint16(m.ByteLow)<<8
	// ByteHigh
	buf[1] = buf[1] | uint16(m.ByteHigh)
	// Int8Low
	buf[2] = buf[2] | uint16(uint8(m.Int8Low))<<8
	// Int8High
	buf[2] = buf[2] | uint16(uint8(m.Int8High))
	// Uint16
	buf[3] = bits.ReverseBytes16(uint16(m.Uint16))
	// Int16
	buf[4] = bits.ReverseBytes16(uint16(m.Int16))
	// Uint32
	buf[5] = bits.ReverseBytes16(uint16(m.Uint32))
	buf[6] = bits.ReverseBytes16(uint16(m.Uint32>>16))
	// Int32
	buf[7] = bits.ReverseBytes16(uint16(m.Int32))
	buf[8] = bits.ReverseBytes16(uint16(m.Int32>>16))
	// Uint64
	buf[9] = bits.ReverseBytes16(uint16(m.Uint64))
	buf[10] = bits.ReverseBytes16(uint16(m.Uint64>>16))
	buf[11] = bits.ReverseBytes16(uint16(m.Uint64>>32))
	buf[12] = bits.ReverseBytes16(uint16(m.Uint64>>48))
	// Int64
	buf[13] = bits.ReverseBytes16(uint16(m.Int64))
	buf[14] = bits.ReverseBytes16(uint16(m.Int64>>16))
	buf[15] = bits.ReverseBytes16(uint16(m.Int64>>32))
	buf[16] = bits.ReverseBytes16(uint16(m.Int64>>48))
	// Float32
	tmp32 = math.Float32bits(float32(m.Float32))
	buf[17] = bits.ReverseBytes16(uint16(tmp32))
	buf[18] = bits.ReverseBytes16(uint16(tmp32>>16))
	// Float64
	tmp64 = math.Float64bits(float64(m.Float64))
	buf[21] = bits.ReverseBytes16(uint16(tmp64))
	buf[22] = bits.ReverseBytes16(uint16(tmp64>>16))
	buf[23] = bits.ReverseBytes16(uint16(tmp64>>32))
	buf[24] = bits.ReverseBytes16(uint16(tmp64>>48))
	// StringASCII8
	length := len(m.StringASCII8)
	for i := 0; i < length; i+=2 {
		if i >= 18 {break}
		b1 := m.StringASCII8[i]
		var b2 byte
		if i+1 < length {b2 = m.StringASCII8[i+1]}
		buf[25+i/2] = uint16(b1)<<8 | uint16(b2)
	}
	// StringASCII16
	for i := 0; i < len(m.StringASCII16); i++ {
		if i >= 9 {break}
		buf[34+i] = uint16(m.StringASCII16[i])<<8
	}
	// StringUTF816
	i = 0
	for _, r := range m.StringUTF816 {
		if i >= 9 {break}
		buf[43+i] = uint16(r>>8) | uint16(r<<8)
		i++
	}

	return buf, nil
}

func (m *LittleEndianLowWordAllCustomExtern) Unmarshal(buf []uint16) error {
	var bytes []byte
	var runes []rune
	var tmp32 uint32
	var tmp64 uint64
	// Uint8Low
	m.Uint8Low = extern.CustomUint8(buf[0]>>8)
	// Uint8High
	m.Uint8High = extern.CustomUint8(buf[0])
	// ByteLow
	m.ByteLow = extern.CustomByte(buf[1]>>8)
	// ByteHigh
	m.ByteHigh = extern.CustomByte(buf[1])
	// Int8Low
	m.Int8Low = extern.CustomInt8(buf[2]>>8)
	// Int8High
	m.Int8High = extern.CustomInt8(buf[2])
	// Uint16
	m.Uint16 = extern.CustomUint16(bits.ReverseBytes16(buf[3]))
	// Int16
	m.Int16 = extern.CustomInt16(bits.ReverseBytes16(buf[4]))
	// Uint32
	m.Uint32 = extern.CustomUint32(bits.ReverseBytes16(buf[5])) | extern.CustomUint32(bits.ReverseBytes16(buf[6])) << 16
	// Int32
	m.Int32 = extern.CustomInt32(int32(bits.ReverseBytes16(buf[7])) | int32(bits.ReverseBytes16(buf[8]))<<16)
	// Uint64
	m.Uint64 = extern.CustomUint64(bits.ReverseBytes16(buf[9])) | extern.CustomUint64(bits.ReverseBytes16(buf[10])) << 16 | extern.CustomUint64(bits.ReverseBytes16(buf[11])) << 32 | extern.CustomUint64(bits.ReverseBytes16(buf[12])) << 48
	// Int64
	m.Int64 = extern.CustomInt64(int64(bits.ReverseBytes16(buf[13])) | int64(bits.ReverseBytes16(buf[14])) << 16 | int64(bits.ReverseBytes16(buf[15])) << 32 | int64(bits.ReverseBytes16(buf[16])) << 48)
	// Float32
	tmp32 = uint32(bits.ReverseBytes16(buf[17])) | uint32(bits.ReverseBytes16(buf[18])) << 16
	m.Float32 = extern.CustomFloat32(math.Float32frombits(tmp32))
	// Float64
	tmp64 = uint64(bits.ReverseBytes16(buf[21])) | uint64(bits.ReverseBytes16(buf[22])) << 16 | uint64(bits.ReverseBytes16(buf[23])) << 32 | uint64(bits.ReverseBytes16(buf[24])) << 48
	m.Float64 = extern.CustomFloat64(math.Float64frombits(tmp64))
	// StringASCII8
	bytes = make([]byte, 18)
	for i, v := range buf[25:34] {
		low := byte(v>>8)
		if low == 0 {bytes = bytes[:i*2];break} // stop on empty char
		bytes[i*2] = low
		high := byte(v)
		if high == 0 {bytes = bytes[:i*2+1];break} // stop on empty char
		bytes[i*2+1] = high
	}
	m.StringASCII8 = extern.CustomString(bytes)
	// StringASCII16
	bytes = make([]byte, 9)
	for i, v := range buf[34:43] {
		if v == 0 {bytes = bytes[:i];break} // stop on empty char
		bytes[i] = byte(v>>8)
	}
	m.StringASCII16 = extern.CustomString(bytes)
	// StringUTF816
	runes = make([]rune, 9)
	for i, v := range buf[43:52] {
		if v == 0 {runes = runes[:i];break} // stop on empty char
		runes[i] = rune(v>>8) | rune(v<<8)
	}
	m.StringUTF816 = extern.CustomString(runes)

	return nil
}

