// Code generated by protoreg. DO NOT EDIT.
package tests

import (
	"math"
	"math/bits"

	"github.com/nocccer/protoreg/tests/extern"
)

func (m LittleEndianLowWord) Marshal() ([]uint16, error) {
	buf := make([]uint16, 104)
	var i int
	var tmp16 uint16
	var tmp32 uint32
	var tmp64 uint64
	// Uint8Low
	buf[0] = buf[0] | uint16(m.Uint8Low) << 8
	// Uint8High
	buf[0] = buf[0] | uint16(m.Uint8High)
	// ByteLow
	buf[1] = buf[1] | uint16(m.ByteLow) << 8
	// ByteHigh
	buf[1] = buf[1] | uint16(m.ByteHigh)
	// Int8Low
	buf[2] = buf[2] | uint16(uint8(m.Int8Low)) << 8
	// Int8High
	buf[2] = buf[2] | uint16(uint8(m.Int8High))
	// Uint16
	buf[3] = bits.ReverseBytes16(m.Uint16)
	// Int16
	buf[4] = bits.ReverseBytes16(uint16(m.Int16))
	// Uint32
	buf[5] = bits.ReverseBytes16(uint16(m.Uint32))
	buf[6] = bits.ReverseBytes16(uint16(m.Uint32 >> 16))
	// Int32
	buf[7] = bits.ReverseBytes16(uint16(m.Int32))
	buf[8] = bits.ReverseBytes16(uint16(m.Int32 >> 16))
	// Uint64
	buf[9] = bits.ReverseBytes16(uint16(m.Uint64))
	buf[10] = bits.ReverseBytes16(uint16(m.Uint64 >> 16))
	buf[11] = bits.ReverseBytes16(uint16(m.Uint64 >> 32))
	buf[12] = bits.ReverseBytes16(uint16(m.Uint64 >> 48))
	// Int64
	buf[13] = bits.ReverseBytes16(uint16(m.Int64))
	buf[14] = bits.ReverseBytes16(uint16(m.Int64 >> 16))
	buf[15] = bits.ReverseBytes16(uint16(m.Int64 >> 32))
	buf[16] = bits.ReverseBytes16(uint16(m.Int64 >> 48))
	// Float32
	tmp32 = math.Float32bits(float32(m.Float32))
	buf[17] = bits.ReverseBytes16(uint16(tmp32))
	buf[18] = bits.ReverseBytes16(uint16(tmp32 >> 16))
	// Float64
	tmp64 = math.Float64bits(float64(m.Float64))
	buf[21] = bits.ReverseBytes16(uint16(tmp64))
	buf[22] = bits.ReverseBytes16(uint16(tmp64 >> 16))
	buf[23] = bits.ReverseBytes16(uint16(tmp64 >> 32))
	buf[24] = bits.ReverseBytes16(uint16(tmp64 >> 48))
	// StringASCII8
	length := len(m.StringASCII8)
	for i := 0; i < length; i+=2 {
		if i >= 18 {break}
		b1 := m.StringASCII8[i]
		var b2 byte
		if i+1 < length {b2 = m.StringASCII8[i+1]}
		buf[25+i/2] = uint16(b1) | uint16(b2) << 8
	}
	// StringASCII16
	for i := 0; i < len(m.StringASCII16); i++ {
		if i >= 9 {break}
		buf[34+i] = uint16(m.StringASCII16[i])<<8
	}
	// StringUTF816
	i = 0
	for _, r := range m.StringUTF816 {
		if i >= 9 {break}
		buf[43+i] = uint16(r >> 8) | uint16(r << 8)
		i++
	}
	// Bool
	tmp16 = 0; if m.Bool {tmp16 = 1}
	buf[52] |= bits.ReverseBytes16(tmp16 << 0)
	// Bit1
	tmp16 = 0; if m.Bit1 {tmp16 = 1}
	buf[53] |= bits.ReverseBytes16(tmp16 << 1)
	// Bit3
	tmp16 = 0; if m.Bit3 {tmp16 = 1}
	buf[53] |= bits.ReverseBytes16(tmp16 << 3)
	// Bit14
	tmp16 = 0; if m.Bit14 {tmp16 = 1}
	buf[53] |= bits.ReverseBytes16(tmp16 << 14)
	// Uint16Array[0]
	buf[54] = bits.ReverseBytes16(m.Uint16Array[0])
	// Uint16Array[1]
	buf[55] = bits.ReverseBytes16(m.Uint16Array[1])
	// Uint16Array[2]
	buf[56] = bits.ReverseBytes16(m.Uint16Array[2])
	// Uint16Array[3]
	buf[57] = bits.ReverseBytes16(m.Uint16Array[3])
	// Uint16Array[4]
	buf[58] = bits.ReverseBytes16(m.Uint16Array[4])
	// Uint32Array[0]
	buf[59] = bits.ReverseBytes16(uint16(m.Uint32Array[0]))
	buf[60] = bits.ReverseBytes16(uint16(m.Uint32Array[0] >> 16))
	// Uint32Array[1]
	buf[63] = bits.ReverseBytes16(uint16(m.Uint32Array[1]))
	buf[64] = bits.ReverseBytes16(uint16(m.Uint32Array[1] >> 16))
	// Uint32Array[2]
	buf[67] = bits.ReverseBytes16(uint16(m.Uint32Array[2]))
	buf[68] = bits.ReverseBytes16(uint16(m.Uint32Array[2] >> 16))
	// Uint32Array[3]
	buf[71] = bits.ReverseBytes16(uint16(m.Uint32Array[3]))
	buf[72] = bits.ReverseBytes16(uint16(m.Uint32Array[3] >> 16))
	// Uint32Array[4]
	buf[75] = bits.ReverseBytes16(uint16(m.Uint32Array[4]))
	buf[76] = bits.ReverseBytes16(uint16(m.Uint32Array[4] >> 16))
	// Float32Array[0]
	tmp32 = math.Float32bits(float32(m.Float32Array[0]))
	buf[79] = bits.ReverseBytes16(uint16(tmp32))
	buf[80] = bits.ReverseBytes16(uint16(tmp32 >> 16))
	// Float32Array[1]
	tmp32 = math.Float32bits(float32(m.Float32Array[1]))
	buf[81] = bits.ReverseBytes16(uint16(tmp32))
	buf[82] = bits.ReverseBytes16(uint16(tmp32 >> 16))
	// Float32Array[2]
	tmp32 = math.Float32bits(float32(m.Float32Array[2]))
	buf[83] = bits.ReverseBytes16(uint16(tmp32))
	buf[84] = bits.ReverseBytes16(uint16(tmp32 >> 16))
	// Float32Array[3]
	tmp32 = math.Float32bits(float32(m.Float32Array[3]))
	buf[85] = bits.ReverseBytes16(uint16(tmp32))
	buf[86] = bits.ReverseBytes16(uint16(tmp32 >> 16))
	// Float32Array[4]
	tmp32 = math.Float32bits(float32(m.Float32Array[4]))
	buf[87] = bits.ReverseBytes16(uint16(tmp32))
	buf[88] = bits.ReverseBytes16(uint16(tmp32 >> 16))
	// BoolArray[0]
	tmp16 = 0; if m.BoolArray[0] {tmp16 = 1}
	buf[89] |= bits.ReverseBytes16(tmp16 << 0)
	// BoolArray[1]
	tmp16 = 0; if m.BoolArray[1] {tmp16 = 1}
	buf[90] |= bits.ReverseBytes16(tmp16 << 0)
	// BoolArray[2]
	tmp16 = 0; if m.BoolArray[2] {tmp16 = 1}
	buf[91] |= bits.ReverseBytes16(tmp16 << 0)
	// BoolArray[3]
	tmp16 = 0; if m.BoolArray[3] {tmp16 = 1}
	buf[92] |= bits.ReverseBytes16(tmp16 << 0)
	// BoolArray[4]
	tmp16 = 0; if m.BoolArray[4] {tmp16 = 1}
	buf[93] |= bits.ReverseBytes16(tmp16 << 0)
	// StringASCII32
	for i := 0; i < len(m.StringASCII32); i++ {
		if i >= 2 {break}
		tmp32 = uint32(m.StringASCII32[i])
		buf[96+i*2] = uint16(tmp32)>>8 | uint16(tmp32)<<8
		buf[96+i*2+1] = uint16(tmp32>>16)>>8 | uint16(tmp32>>16)<<8
	}
	// StringUTF832
	i = 0
	for _, r := range m.StringUTF832 {
		if i >= 2 {break}
		tmp32 = uint32(r)
		buf[100+i*2] = uint16(tmp32)>>8 | uint16(tmp32)<<8
		buf[100+i*2+1] = uint16(tmp32>>16)>>8 | uint16(tmp32>>16)<<8
		i++
	}

	return buf, nil
}

func (m *LittleEndianLowWord) Unmarshal(buf []uint16) error {
	var bytes []byte
	var runes []rune
	var tmp16 uint16
	var tmp32 uint32
	var tmp64 uint64
	// Uint8Low
	m.Uint8Low = uint8(buf[0] >> 8)
	// Uint8High
	m.Uint8High = uint8(buf[0])
	// ByteLow
	m.ByteLow = uint8(buf[1] >> 8)
	// ByteHigh
	m.ByteHigh = uint8(buf[1])
	// Int8Low
	m.Int8Low = int8(buf[2] >> 8)
	// Int8High
	m.Int8High = int8(buf[2])
	// Uint16
	m.Uint16 = bits.ReverseBytes16(buf[3])
	// Int16
	m.Int16 = int16(bits.ReverseBytes16(buf[4]))
	// Uint32
	m.Uint32 = uint32(bits.ReverseBytes16(buf[5])) | uint32(bits.ReverseBytes16(buf[6])) << 16
	// Int32
	m.Int32 = int32(bits.ReverseBytes16(buf[7])) | int32(bits.ReverseBytes16(buf[8])) << 16
	// Uint64
	m.Uint64 = uint64(bits.ReverseBytes16(buf[9])) | uint64(bits.ReverseBytes16(buf[10])) << 16 | uint64(bits.ReverseBytes16(buf[11])) << 32 | uint64(bits.ReverseBytes16(buf[12])) << 48
	// Int64
	m.Int64 = int64(bits.ReverseBytes16(buf[13])) | int64(bits.ReverseBytes16(buf[14])) << 16 | int64(bits.ReverseBytes16(buf[15])) << 32 | int64(bits.ReverseBytes16(buf[16])) << 48
	// Float32
	tmp32 = uint32(bits.ReverseBytes16(buf[17])) | uint32(bits.ReverseBytes16(buf[18])) << 16
	m.Float32 = math.Float32frombits(tmp32)
	// Float64
	tmp64 = uint64(bits.ReverseBytes16(buf[21])) | uint64(bits.ReverseBytes16(buf[22])) << 16 | uint64(bits.ReverseBytes16(buf[23])) << 32 | uint64(bits.ReverseBytes16(buf[24])) << 48
	m.Float64 = math.Float64frombits(tmp64)
	// StringASCII8
	bytes = make([]byte, 18)
	for i, v := range buf[25:34] {
		first := byte(v)
		if first == 0 {bytes = bytes[:i*2];break} // stop on empty char
		bytes[i*2] = first
		second := byte(v >> 8)
		if second == 0 {bytes = bytes[:i*2+1];break} // stop on empty char
		bytes[i*2+1] = second
	}
	m.StringASCII8 = string(bytes)
	// StringASCII16
	bytes = make([]byte, 9)
	for i, v := range buf[34:43] {
		if v == 0 {bytes = bytes[:i];break} // stop on empty char
		bytes[i] = byte(v>>8)
	}
	m.StringASCII16 = string(bytes)
	// StringUTF816
	runes = make([]rune, 9)
	for i, v := range buf[43:52] {
		if v == 0 {runes = runes[:i];break} // stop on empty char
		runes[i] = rune(v >> 8) | rune(v << 8)
	}
	m.StringUTF816 = string(runes)
	// Bool
	tmp16 = bits.ReverseBytes16(buf[52]) & 0x0001
	if tmp16 != 0 { m.Bool = true } else { m.Bool = false }
	// Bit1
	tmp16 = bits.ReverseBytes16(buf[53]) & 0x0002
	if tmp16 != 0 { m.Bit1 = true } else { m.Bit1 = false }
	// Bit3
	tmp16 = bits.ReverseBytes16(buf[53]) & 0x0008
	if tmp16 != 0 { m.Bit3 = true } else { m.Bit3 = false }
	// Bit14
	tmp16 = bits.ReverseBytes16(buf[53]) & 0x4000
	if tmp16 != 0 { m.Bit14 = true } else { m.Bit14 = false }
	// Uint16Array[0]
	m.Uint16Array[0] = bits.ReverseBytes16(buf[54])
	// Uint16Array[1]
	m.Uint16Array[1] = bits.ReverseBytes16(buf[55])
	// Uint16Array[2]
	m.Uint16Array[2] = bits.ReverseBytes16(buf[56])
	// Uint16Array[3]
	m.Uint16Array[3] = bits.ReverseBytes16(buf[57])
	// Uint16Array[4]
	m.Uint16Array[4] = bits.ReverseBytes16(buf[58])
	// Uint32Array[0]
	m.Uint32Array[0] = uint32(bits.ReverseBytes16(buf[59])) | uint32(bits.ReverseBytes16(buf[60])) << 16
	// Uint32Array[1]
	m.Uint32Array[1] = uint32(bits.ReverseBytes16(buf[63])) | uint32(bits.ReverseBytes16(buf[64])) << 16
	// Uint32Array[2]
	m.Uint32Array[2] = uint32(bits.ReverseBytes16(buf[67])) | uint32(bits.ReverseBytes16(buf[68])) << 16
	// Uint32Array[3]
	m.Uint32Array[3] = uint32(bits.ReverseBytes16(buf[71])) | uint32(bits.ReverseBytes16(buf[72])) << 16
	// Uint32Array[4]
	m.Uint32Array[4] = uint32(bits.ReverseBytes16(buf[75])) | uint32(bits.ReverseBytes16(buf[76])) << 16
	// Float32Array[0]
	tmp32 = uint32(bits.ReverseBytes16(buf[79])) | uint32(bits.ReverseBytes16(buf[80])) << 16
	m.Float32Array[0] = math.Float32frombits(tmp32)
	// Float32Array[1]
	tmp32 = uint32(bits.ReverseBytes16(buf[81])) | uint32(bits.ReverseBytes16(buf[82])) << 16
	m.Float32Array[1] = math.Float32frombits(tmp32)
	// Float32Array[2]
	tmp32 = uint32(bits.ReverseBytes16(buf[83])) | uint32(bits.ReverseBytes16(buf[84])) << 16
	m.Float32Array[2] = math.Float32frombits(tmp32)
	// Float32Array[3]
	tmp32 = uint32(bits.ReverseBytes16(buf[85])) | uint32(bits.ReverseBytes16(buf[86])) << 16
	m.Float32Array[3] = math.Float32frombits(tmp32)
	// Float32Array[4]
	tmp32 = uint32(bits.ReverseBytes16(buf[87])) | uint32(bits.ReverseBytes16(buf[88])) << 16
	m.Float32Array[4] = math.Float32frombits(tmp32)
	// BoolArray[0]
	tmp16 = bits.ReverseBytes16(buf[89]) & 0x0001
	if tmp16 != 0 { m.BoolArray[0] = true } else { m.BoolArray[0] = false }
	// BoolArray[1]
	tmp16 = bits.ReverseBytes16(buf[90]) & 0x0001
	if tmp16 != 0 { m.BoolArray[1] = true } else { m.BoolArray[1] = false }
	// BoolArray[2]
	tmp16 = bits.ReverseBytes16(buf[91]) & 0x0001
	if tmp16 != 0 { m.BoolArray[2] = true } else { m.BoolArray[2] = false }
	// BoolArray[3]
	tmp16 = bits.ReverseBytes16(buf[92]) & 0x0001
	if tmp16 != 0 { m.BoolArray[3] = true } else { m.BoolArray[3] = false }
	// BoolArray[4]
	tmp16 = bits.ReverseBytes16(buf[93]) & 0x0001
	if tmp16 != 0 { m.BoolArray[4] = true } else { m.BoolArray[4] = false }
	// StringASCII32
	bytes = make([]byte, 0, 2)
	for i := 0; i < 2; i++ {
		first := uint16(buf[96+i*2] >> 8) | uint16(buf[96+i*2] << 8)
		second := uint16(buf[96+i*2+1] >> 8) | uint16(buf[96+i*2+1] << 8)
		tmp32 = uint32(first) | uint32(second) << 16
		if tmp32 == 0 {break} // stop on empty char
		bytes = append(bytes, byte(tmp32))
	}
	m.StringASCII32 = string(bytes)
	// StringUTF832
	runes = make([]rune, 0, 2)
	for i := 0; i < 2; i++ {
		first := uint16(buf[100+i*2] >> 8) | uint16(buf[100+i*2] << 8)
		second := uint16(buf[100+i*2+1] >> 8) | uint16(buf[100+i*2+1] << 8)
		tmp32 = uint32(first) | uint32(second) << 16
		if tmp32 == 0 {break} // stop on empty char
		runes = append(runes, rune(tmp32))
	}
	m.StringUTF832 = string(runes)

	return nil
}

func (m LittleEndianLowWordAllCustom) Marshal() ([]uint16, error) {
	buf := make([]uint16, 104)
	var i int
	var tmp16 uint16
	var tmp32 uint32
	var tmp64 uint64
	// Uint8Low
	buf[0] = buf[0] | uint16(m.Uint8Low) << 8
	// Uint8High
	buf[0] = buf[0] | uint16(m.Uint8High)
	// ByteLow
	buf[1] = buf[1] | uint16(m.ByteLow) << 8
	// ByteHigh
	buf[1] = buf[1] | uint16(m.ByteHigh)
	// Int8Low
	buf[2] = buf[2] | uint16(uint8(m.Int8Low)) << 8
	// Int8High
	buf[2] = buf[2] | uint16(uint8(m.Int8High))
	// Uint16
	buf[3] = bits.ReverseBytes16(uint16(m.Uint16))
	// Int16
	buf[4] = bits.ReverseBytes16(uint16(m.Int16))
	// Uint32
	buf[5] = bits.ReverseBytes16(uint16(m.Uint32))
	buf[6] = bits.ReverseBytes16(uint16(m.Uint32 >> 16))
	// Int32
	buf[7] = bits.ReverseBytes16(uint16(m.Int32))
	buf[8] = bits.ReverseBytes16(uint16(m.Int32 >> 16))
	// Uint64
	buf[9] = bits.ReverseBytes16(uint16(m.Uint64))
	buf[10] = bits.ReverseBytes16(uint16(m.Uint64 >> 16))
	buf[11] = bits.ReverseBytes16(uint16(m.Uint64 >> 32))
	buf[12] = bits.ReverseBytes16(uint16(m.Uint64 >> 48))
	// Int64
	buf[13] = bits.ReverseBytes16(uint16(m.Int64))
	buf[14] = bits.ReverseBytes16(uint16(m.Int64 >> 16))
	buf[15] = bits.ReverseBytes16(uint16(m.Int64 >> 32))
	buf[16] = bits.ReverseBytes16(uint16(m.Int64 >> 48))
	// Float32
	tmp32 = math.Float32bits(float32(m.Float32))
	buf[17] = bits.ReverseBytes16(uint16(tmp32))
	buf[18] = bits.ReverseBytes16(uint16(tmp32 >> 16))
	// Float64
	tmp64 = math.Float64bits(float64(m.Float64))
	buf[21] = bits.ReverseBytes16(uint16(tmp64))
	buf[22] = bits.ReverseBytes16(uint16(tmp64 >> 16))
	buf[23] = bits.ReverseBytes16(uint16(tmp64 >> 32))
	buf[24] = bits.ReverseBytes16(uint16(tmp64 >> 48))
	// StringASCII8
	length := len(m.StringASCII8)
	for i := 0; i < length; i+=2 {
		if i >= 18 {break}
		b1 := m.StringASCII8[i]
		var b2 byte
		if i+1 < length {b2 = m.StringASCII8[i+1]}
		buf[25+i/2] = uint16(b1) | uint16(b2) << 8
	}
	// StringASCII16
	for i := 0; i < len(m.StringASCII16); i++ {
		if i >= 9 {break}
		buf[34+i] = uint16(m.StringASCII16[i])<<8
	}
	// StringUTF816
	i = 0
	for _, r := range m.StringUTF816 {
		if i >= 9 {break}
		buf[43+i] = uint16(r >> 8) | uint16(r << 8)
		i++
	}
	// Bool
	tmp16 = 0; if m.Bool {tmp16 = 1}
	buf[52] |= bits.ReverseBytes16(tmp16 << 0)
	// Bit1
	tmp16 = 0; if m.Bit1 {tmp16 = 1}
	buf[53] |= bits.ReverseBytes16(tmp16 << 1)
	// Bit3
	tmp16 = 0; if m.Bit3 {tmp16 = 1}
	buf[53] |= bits.ReverseBytes16(tmp16 << 3)
	// Bit14
	tmp16 = 0; if m.Bit14 {tmp16 = 1}
	buf[53] |= bits.ReverseBytes16(tmp16 << 14)
	// Uint16Array[0]
	buf[54] = bits.ReverseBytes16(uint16(m.Uint16Array[0]))
	// Uint16Array[1]
	buf[55] = bits.ReverseBytes16(uint16(m.Uint16Array[1]))
	// Uint16Array[2]
	buf[56] = bits.ReverseBytes16(uint16(m.Uint16Array[2]))
	// Uint16Array[3]
	buf[57] = bits.ReverseBytes16(uint16(m.Uint16Array[3]))
	// Uint16Array[4]
	buf[58] = bits.ReverseBytes16(uint16(m.Uint16Array[4]))
	// Uint32Array[0]
	buf[59] = bits.ReverseBytes16(uint16(m.Uint32Array[0]))
	buf[60] = bits.ReverseBytes16(uint16(m.Uint32Array[0] >> 16))
	// Uint32Array[1]
	buf[63] = bits.ReverseBytes16(uint16(m.Uint32Array[1]))
	buf[64] = bits.ReverseBytes16(uint16(m.Uint32Array[1] >> 16))
	// Uint32Array[2]
	buf[67] = bits.ReverseBytes16(uint16(m.Uint32Array[2]))
	buf[68] = bits.ReverseBytes16(uint16(m.Uint32Array[2] >> 16))
	// Uint32Array[3]
	buf[71] = bits.ReverseBytes16(uint16(m.Uint32Array[3]))
	buf[72] = bits.ReverseBytes16(uint16(m.Uint32Array[3] >> 16))
	// Uint32Array[4]
	buf[75] = bits.ReverseBytes16(uint16(m.Uint32Array[4]))
	buf[76] = bits.ReverseBytes16(uint16(m.Uint32Array[4] >> 16))
	// Float32Array[0]
	tmp32 = math.Float32bits(float32(m.Float32Array[0]))
	buf[79] = bits.ReverseBytes16(uint16(tmp32))
	buf[80] = bits.ReverseBytes16(uint16(tmp32 >> 16))
	// Float32Array[1]
	tmp32 = math.Float32bits(float32(m.Float32Array[1]))
	buf[81] = bits.ReverseBytes16(uint16(tmp32))
	buf[82] = bits.ReverseBytes16(uint16(tmp32 >> 16))
	// Float32Array[2]
	tmp32 = math.Float32bits(float32(m.Float32Array[2]))
	buf[83] = bits.ReverseBytes16(uint16(tmp32))
	buf[84] = bits.ReverseBytes16(uint16(tmp32 >> 16))
	// Float32Array[3]
	tmp32 = math.Float32bits(float32(m.Float32Array[3]))
	buf[85] = bits.ReverseBytes16(uint16(tmp32))
	buf[86] = bits.ReverseBytes16(uint16(tmp32 >> 16))
	// Float32Array[4]
	tmp32 = math.Float32bits(float32(m.Float32Array[4]))
	buf[87] = bits.ReverseBytes16(uint16(tmp32))
	buf[88] = bits.ReverseBytes16(uint16(tmp32 >> 16))
	// BoolArray[0]
	tmp16 = 0; if m.BoolArray[0] {tmp16 = 1}
	buf[89] |= bits.ReverseBytes16(tmp16 << 0)
	// BoolArray[1]
	tmp16 = 0; if m.BoolArray[1] {tmp16 = 1}
	buf[90] |= bits.ReverseBytes16(tmp16 << 0)
	// BoolArray[2]
	tmp16 = 0; if m.BoolArray[2] {tmp16 = 1}
	buf[91] |= bits.ReverseBytes16(tmp16 << 0)
	// BoolArray[3]
	tmp16 = 0; if m.BoolArray[3] {tmp16 = 1}
	buf[92] |= bits.ReverseBytes16(tmp16 << 0)
	// BoolArray[4]
	tmp16 = 0; if m.BoolArray[4] {tmp16 = 1}
	buf[93] |= bits.ReverseBytes16(tmp16 << 0)
	// BitField16
	buf[94] = bits.ReverseBytes16(uint16(m.BitField16))
	// StringASCII32
	for i := 0; i < len(m.StringASCII32); i++ {
		if i >= 2 {break}
		tmp32 = uint32(m.StringASCII32[i])
		buf[96+i*2] = uint16(tmp32)>>8 | uint16(tmp32)<<8
		buf[96+i*2+1] = uint16(tmp32>>16)>>8 | uint16(tmp32>>16)<<8
	}
	// StringUTF832
	i = 0
	for _, r := range m.StringUTF832 {
		if i >= 2 {break}
		tmp32 = uint32(r)
		buf[100+i*2] = uint16(tmp32)>>8 | uint16(tmp32)<<8
		buf[100+i*2+1] = uint16(tmp32>>16)>>8 | uint16(tmp32>>16)<<8
		i++
	}

	return buf, nil
}

func (m *LittleEndianLowWordAllCustom) Unmarshal(buf []uint16) error {
	var bytes []byte
	var runes []rune
	var tmp16 uint16
	var tmp32 uint32
	var tmp64 uint64
	// Uint8Low
	m.Uint8Low = CustomUint8(buf[0] >> 8)
	// Uint8High
	m.Uint8High = CustomUint8(buf[0])
	// ByteLow
	m.ByteLow = CustomByte(buf[1] >> 8)
	// ByteHigh
	m.ByteHigh = CustomByte(buf[1])
	// Int8Low
	m.Int8Low = CustomInt8(buf[2] >> 8)
	// Int8High
	m.Int8High = CustomInt8(buf[2])
	// Uint16
	m.Uint16 = CustomUint16(bits.ReverseBytes16(buf[3]))
	// Int16
	m.Int16 = CustomInt16(bits.ReverseBytes16(buf[4]))
	// Uint32
	m.Uint32 = CustomUint32(bits.ReverseBytes16(buf[5])) | CustomUint32(bits.ReverseBytes16(buf[6])) << 16
	// Int32
	m.Int32 = CustomInt32(int32(bits.ReverseBytes16(buf[7])) | int32(bits.ReverseBytes16(buf[8])) << 16)
	// Uint64
	m.Uint64 = CustomUint64(bits.ReverseBytes16(buf[9])) | CustomUint64(bits.ReverseBytes16(buf[10])) << 16 | CustomUint64(bits.ReverseBytes16(buf[11])) << 32 | CustomUint64(bits.ReverseBytes16(buf[12])) << 48
	// Int64
	m.Int64 = CustomInt64(int64(bits.ReverseBytes16(buf[13])) | int64(bits.ReverseBytes16(buf[14])) << 16 | int64(bits.ReverseBytes16(buf[15])) << 32 | int64(bits.ReverseBytes16(buf[16])) << 48)
	// Float32
	tmp32 = uint32(bits.ReverseBytes16(buf[17])) | uint32(bits.ReverseBytes16(buf[18])) << 16
	m.Float32 = CustomFloat32(math.Float32frombits(tmp32))
	// Float64
	tmp64 = uint64(bits.ReverseBytes16(buf[21])) | uint64(bits.ReverseBytes16(buf[22])) << 16 | uint64(bits.ReverseBytes16(buf[23])) << 32 | uint64(bits.ReverseBytes16(buf[24])) << 48
	m.Float64 = CustomFloat64(math.Float64frombits(tmp64))
	// StringASCII8
	bytes = make([]byte, 18)
	for i, v := range buf[25:34] {
		first := byte(v)
		if first == 0 {bytes = bytes[:i*2];break} // stop on empty char
		bytes[i*2] = first
		second := byte(v >> 8)
		if second == 0 {bytes = bytes[:i*2+1];break} // stop on empty char
		bytes[i*2+1] = second
	}
	m.StringASCII8 = CustomString(bytes)
	// StringASCII16
	bytes = make([]byte, 9)
	for i, v := range buf[34:43] {
		if v == 0 {bytes = bytes[:i];break} // stop on empty char
		bytes[i] = byte(v>>8)
	}
	m.StringASCII16 = CustomString(bytes)
	// StringUTF816
	runes = make([]rune, 9)
	for i, v := range buf[43:52] {
		if v == 0 {runes = runes[:i];break} // stop on empty char
		runes[i] = rune(v >> 8) | rune(v << 8)
	}
	m.StringUTF816 = CustomString(runes)
	// Bool
	tmp16 = bits.ReverseBytes16(buf[52]) & 0x0001
	if tmp16 != 0 { m.Bool = true } else { m.Bool = false }
	// Bit1
	tmp16 = bits.ReverseBytes16(buf[53]) & 0x0002
	if tmp16 != 0 { m.Bit1 = true } else { m.Bit1 = false }
	// Bit3
	tmp16 = bits.ReverseBytes16(buf[53]) & 0x0008
	if tmp16 != 0 { m.Bit3 = true } else { m.Bit3 = false }
	// Bit14
	tmp16 = bits.ReverseBytes16(buf[53]) & 0x4000
	if tmp16 != 0 { m.Bit14 = true } else { m.Bit14 = false }
	// Uint16Array[0]
	m.Uint16Array[0] = CustomUint16(bits.ReverseBytes16(buf[54]))
	// Uint16Array[1]
	m.Uint16Array[1] = CustomUint16(bits.ReverseBytes16(buf[55]))
	// Uint16Array[2]
	m.Uint16Array[2] = CustomUint16(bits.ReverseBytes16(buf[56]))
	// Uint16Array[3]
	m.Uint16Array[3] = CustomUint16(bits.ReverseBytes16(buf[57]))
	// Uint16Array[4]
	m.Uint16Array[4] = CustomUint16(bits.ReverseBytes16(buf[58]))
	// Uint32Array[0]
	m.Uint32Array[0] = CustomUint32(bits.ReverseBytes16(buf[59])) | CustomUint32(bits.ReverseBytes16(buf[60])) << 16
	// Uint32Array[1]
	m.Uint32Array[1] = CustomUint32(bits.ReverseBytes16(buf[63])) | CustomUint32(bits.ReverseBytes16(buf[64])) << 16
	// Uint32Array[2]
	m.Uint32Array[2] = CustomUint32(bits.ReverseBytes16(buf[67])) | CustomUint32(bits.ReverseBytes16(buf[68])) << 16
	// Uint32Array[3]
	m.Uint32Array[3] = CustomUint32(bits.ReverseBytes16(buf[71])) | CustomUint32(bits.ReverseBytes16(buf[72])) << 16
	// Uint32Array[4]
	m.Uint32Array[4] = CustomUint32(bits.ReverseBytes16(buf[75])) | CustomUint32(bits.ReverseBytes16(buf[76])) << 16
	// Float32Array[0]
	tmp32 = uint32(bits.ReverseBytes16(buf[79])) | uint32(bits.ReverseBytes16(buf[80])) << 16
	m.Float32Array[0] = CustomFloat32(math.Float32frombits(tmp32))
	// Float32Array[1]
	tmp32 = uint32(bits.ReverseBytes16(buf[81])) | uint32(bits.ReverseBytes16(buf[82])) << 16
	m.Float32Array[1] = CustomFloat32(math.Float32frombits(tmp32))
	// Float32Array[2]
	tmp32 = uint32(bits.ReverseBytes16(buf[83])) | uint32(bits.ReverseBytes16(buf[84])) << 16
	m.Float32Array[2] = CustomFloat32(math.Float32frombits(tmp32))
	// Float32Array[3]
	tmp32 = uint32(bits.ReverseBytes16(buf[85])) | uint32(bits.ReverseBytes16(buf[86])) << 16
	m.Float32Array[3] = CustomFloat32(math.Float32frombits(tmp32))
	// Float32Array[4]
	tmp32 = uint32(bits.ReverseBytes16(buf[87])) | uint32(bits.ReverseBytes16(buf[88])) << 16
	m.Float32Array[4] = CustomFloat32(math.Float32frombits(tmp32))
	// BoolArray[0]
	tmp16 = bits.ReverseBytes16(buf[89]) & 0x0001
	if tmp16 != 0 { m.BoolArray[0] = true } else { m.BoolArray[0] = false }
	// BoolArray[1]
	tmp16 = bits.ReverseBytes16(buf[90]) & 0x0001
	if tmp16 != 0 { m.BoolArray[1] = true } else { m.BoolArray[1] = false }
	// BoolArray[2]
	tmp16 = bits.ReverseBytes16(buf[91]) & 0x0001
	if tmp16 != 0 { m.BoolArray[2] = true } else { m.BoolArray[2] = false }
	// BoolArray[3]
	tmp16 = bits.ReverseBytes16(buf[92]) & 0x0001
	if tmp16 != 0 { m.BoolArray[3] = true } else { m.BoolArray[3] = false }
	// BoolArray[4]
	tmp16 = bits.ReverseBytes16(buf[93]) & 0x0001
	if tmp16 != 0 { m.BoolArray[4] = true } else { m.BoolArray[4] = false }
	// BitField16
	m.BitField16 = BitField16[CustomUint16](bits.ReverseBytes16(buf[94]))
	// StringASCII32
	bytes = make([]byte, 0, 2)
	for i := 0; i < 2; i++ {
		first := uint16(buf[96+i*2] >> 8) | uint16(buf[96+i*2] << 8)
		second := uint16(buf[96+i*2+1] >> 8) | uint16(buf[96+i*2+1] << 8)
		tmp32 = uint32(first) | uint32(second) << 16
		if tmp32 == 0 {break} // stop on empty char
		bytes = append(bytes, byte(tmp32))
	}
	m.StringASCII32 = CustomString(bytes)
	// StringUTF832
	runes = make([]rune, 0, 2)
	for i := 0; i < 2; i++ {
		first := uint16(buf[100+i*2] >> 8) | uint16(buf[100+i*2] << 8)
		second := uint16(buf[100+i*2+1] >> 8) | uint16(buf[100+i*2+1] << 8)
		tmp32 = uint32(first) | uint32(second) << 16
		if tmp32 == 0 {break} // stop on empty char
		runes = append(runes, rune(tmp32))
	}
	m.StringUTF832 = CustomString(runes)

	return nil
}

func (m LittleEndianLowWordAllCustomExtern) Marshal() ([]uint16, error) {
	buf := make([]uint16, 104)
	var i int
	var tmp16 uint16
	var tmp32 uint32
	var tmp64 uint64
	// Uint8Low
	buf[0] = buf[0] | uint16(m.Uint8Low) << 8
	// Uint8High
	buf[0] = buf[0] | uint16(m.Uint8High)
	// ByteLow
	buf[1] = buf[1] | uint16(m.ByteLow) << 8
	// ByteHigh
	buf[1] = buf[1] | uint16(m.ByteHigh)
	// Int8Low
	buf[2] = buf[2] | uint16(uint8(m.Int8Low)) << 8
	// Int8High
	buf[2] = buf[2] | uint16(uint8(m.Int8High))
	// Uint16
	buf[3] = bits.ReverseBytes16(uint16(m.Uint16))
	// Int16
	buf[4] = bits.ReverseBytes16(uint16(m.Int16))
	// Uint32
	buf[5] = bits.ReverseBytes16(uint16(m.Uint32))
	buf[6] = bits.ReverseBytes16(uint16(m.Uint32 >> 16))
	// Int32
	buf[7] = bits.ReverseBytes16(uint16(m.Int32))
	buf[8] = bits.ReverseBytes16(uint16(m.Int32 >> 16))
	// Uint64
	buf[9] = bits.ReverseBytes16(uint16(m.Uint64))
	buf[10] = bits.ReverseBytes16(uint16(m.Uint64 >> 16))
	buf[11] = bits.ReverseBytes16(uint16(m.Uint64 >> 32))
	buf[12] = bits.ReverseBytes16(uint16(m.Uint64 >> 48))
	// Int64
	buf[13] = bits.ReverseBytes16(uint16(m.Int64))
	buf[14] = bits.ReverseBytes16(uint16(m.Int64 >> 16))
	buf[15] = bits.ReverseBytes16(uint16(m.Int64 >> 32))
	buf[16] = bits.ReverseBytes16(uint16(m.Int64 >> 48))
	// Float32
	tmp32 = math.Float32bits(float32(m.Float32))
	buf[17] = bits.ReverseBytes16(uint16(tmp32))
	buf[18] = bits.ReverseBytes16(uint16(tmp32 >> 16))
	// Float64
	tmp64 = math.Float64bits(float64(m.Float64))
	buf[21] = bits.ReverseBytes16(uint16(tmp64))
	buf[22] = bits.ReverseBytes16(uint16(tmp64 >> 16))
	buf[23] = bits.ReverseBytes16(uint16(tmp64 >> 32))
	buf[24] = bits.ReverseBytes16(uint16(tmp64 >> 48))
	// StringASCII8
	length := len(m.StringASCII8)
	for i := 0; i < length; i+=2 {
		if i >= 18 {break}
		b1 := m.StringASCII8[i]
		var b2 byte
		if i+1 < length {b2 = m.StringASCII8[i+1]}
		buf[25+i/2] = uint16(b1) | uint16(b2) << 8
	}
	// StringASCII16
	for i := 0; i < len(m.StringASCII16); i++ {
		if i >= 9 {break}
		buf[34+i] = uint16(m.StringASCII16[i])<<8
	}
	// StringUTF816
	i = 0
	for _, r := range m.StringUTF816 {
		if i >= 9 {break}
		buf[43+i] = uint16(r >> 8) | uint16(r << 8)
		i++
	}
	// Bool
	tmp16 = 0; if m.Bool {tmp16 = 1}
	buf[52] |= bits.ReverseBytes16(tmp16 << 0)
	// Bit1
	tmp16 = 0; if m.Bit1 {tmp16 = 1}
	buf[53] |= bits.ReverseBytes16(tmp16 << 1)
	// Bit3
	tmp16 = 0; if m.Bit3 {tmp16 = 1}
	buf[53] |= bits.ReverseBytes16(tmp16 << 3)
	// Bit14
	tmp16 = 0; if m.Bit14 {tmp16 = 1}
	buf[53] |= bits.ReverseBytes16(tmp16 << 14)
	// Uint16Array[0]
	buf[54] = bits.ReverseBytes16(uint16(m.Uint16Array[0]))
	// Uint16Array[1]
	buf[55] = bits.ReverseBytes16(uint16(m.Uint16Array[1]))
	// Uint16Array[2]
	buf[56] = bits.ReverseBytes16(uint16(m.Uint16Array[2]))
	// Uint16Array[3]
	buf[57] = bits.ReverseBytes16(uint16(m.Uint16Array[3]))
	// Uint16Array[4]
	buf[58] = bits.ReverseBytes16(uint16(m.Uint16Array[4]))
	// Uint32Array[0]
	buf[59] = bits.ReverseBytes16(uint16(m.Uint32Array[0]))
	buf[60] = bits.ReverseBytes16(uint16(m.Uint32Array[0] >> 16))
	// Uint32Array[1]
	buf[63] = bits.ReverseBytes16(uint16(m.Uint32Array[1]))
	buf[64] = bits.ReverseBytes16(uint16(m.Uint32Array[1] >> 16))
	// Uint32Array[2]
	buf[67] = bits.ReverseBytes16(uint16(m.Uint32Array[2]))
	buf[68] = bits.ReverseBytes16(uint16(m.Uint32Array[2] >> 16))
	// Uint32Array[3]
	buf[71] = bits.ReverseBytes16(uint16(m.Uint32Array[3]))
	buf[72] = bits.ReverseBytes16(uint16(m.Uint32Array[3] >> 16))
	// Uint32Array[4]
	buf[75] = bits.ReverseBytes16(uint16(m.Uint32Array[4]))
	buf[76] = bits.ReverseBytes16(uint16(m.Uint32Array[4] >> 16))
	// Float32Array[0]
	tmp32 = math.Float32bits(float32(m.Float32Array[0]))
	buf[79] = bits.ReverseBytes16(uint16(tmp32))
	buf[80] = bits.ReverseBytes16(uint16(tmp32 >> 16))
	// Float32Array[1]
	tmp32 = math.Float32bits(float32(m.Float32Array[1]))
	buf[81] = bits.ReverseBytes16(uint16(tmp32))
	buf[82] = bits.ReverseBytes16(uint16(tmp32 >> 16))
	// Float32Array[2]
	tmp32 = math.Float32bits(float32(m.Float32Array[2]))
	buf[83] = bits.ReverseBytes16(uint16(tmp32))
	buf[84] = bits.ReverseBytes16(uint16(tmp32 >> 16))
	// Float32Array[3]
	tmp32 = math.Float32bits(float32(m.Float32Array[3]))
	buf[85] = bits.ReverseBytes16(uint16(tmp32))
	buf[86] = bits.ReverseBytes16(uint16(tmp32 >> 16))
	// Float32Array[4]
	tmp32 = math.Float32bits(float32(m.Float32Array[4]))
	buf[87] = bits.ReverseBytes16(uint16(tmp32))
	buf[88] = bits.ReverseBytes16(uint16(tmp32 >> 16))
	// BoolArray[0]
	tmp16 = 0; if m.BoolArray[0] {tmp16 = 1}
	buf[89] |= bits.ReverseBytes16(tmp16 << 0)
	// BoolArray[1]
	tmp16 = 0; if m.BoolArray[1] {tmp16 = 1}
	buf[90] |= bits.ReverseBytes16(tmp16 << 0)
	// BoolArray[2]
	tmp16 = 0; if m.BoolArray[2] {tmp16 = 1}
	buf[91] |= bits.ReverseBytes16(tmp16 << 0)
	// BoolArray[3]
	tmp16 = 0; if m.BoolArray[3] {tmp16 = 1}
	buf[92] |= bits.ReverseBytes16(tmp16 << 0)
	// BoolArray[4]
	tmp16 = 0; if m.BoolArray[4] {tmp16 = 1}
	buf[93] |= bits.ReverseBytes16(tmp16 << 0)
	// BitField16
	buf[94] = bits.ReverseBytes16(uint16(m.BitField16))
	// StringASCII32
	for i := 0; i < len(m.StringASCII32); i++ {
		if i >= 2 {break}
		tmp32 = uint32(m.StringASCII32[i])
		buf[96+i*2] = uint16(tmp32)>>8 | uint16(tmp32)<<8
		buf[96+i*2+1] = uint16(tmp32>>16)>>8 | uint16(tmp32>>16)<<8
	}
	// StringUTF832
	i = 0
	for _, r := range m.StringUTF832 {
		if i >= 2 {break}
		tmp32 = uint32(r)
		buf[100+i*2] = uint16(tmp32)>>8 | uint16(tmp32)<<8
		buf[100+i*2+1] = uint16(tmp32>>16)>>8 | uint16(tmp32>>16)<<8
		i++
	}

	return buf, nil
}

func (m *LittleEndianLowWordAllCustomExtern) Unmarshal(buf []uint16) error {
	var bytes []byte
	var runes []rune
	var tmp16 uint16
	var tmp32 uint32
	var tmp64 uint64
	// Uint8Low
	m.Uint8Low = extern.CustomUint8(buf[0] >> 8)
	// Uint8High
	m.Uint8High = extern.CustomUint8(buf[0])
	// ByteLow
	m.ByteLow = extern.CustomByte(buf[1] >> 8)
	// ByteHigh
	m.ByteHigh = extern.CustomByte(buf[1])
	// Int8Low
	m.Int8Low = extern.CustomInt8(buf[2] >> 8)
	// Int8High
	m.Int8High = extern.CustomInt8(buf[2])
	// Uint16
	m.Uint16 = extern.CustomUint16(bits.ReverseBytes16(buf[3]))
	// Int16
	m.Int16 = extern.CustomInt16(bits.ReverseBytes16(buf[4]))
	// Uint32
	m.Uint32 = extern.CustomUint32(bits.ReverseBytes16(buf[5])) | extern.CustomUint32(bits.ReverseBytes16(buf[6])) << 16
	// Int32
	m.Int32 = extern.CustomInt32(int32(bits.ReverseBytes16(buf[7])) | int32(bits.ReverseBytes16(buf[8])) << 16)
	// Uint64
	m.Uint64 = extern.CustomUint64(bits.ReverseBytes16(buf[9])) | extern.CustomUint64(bits.ReverseBytes16(buf[10])) << 16 | extern.CustomUint64(bits.ReverseBytes16(buf[11])) << 32 | extern.CustomUint64(bits.ReverseBytes16(buf[12])) << 48
	// Int64
	m.Int64 = extern.CustomInt64(int64(bits.ReverseBytes16(buf[13])) | int64(bits.ReverseBytes16(buf[14])) << 16 | int64(bits.ReverseBytes16(buf[15])) << 32 | int64(bits.ReverseBytes16(buf[16])) << 48)
	// Float32
	tmp32 = uint32(bits.ReverseBytes16(buf[17])) | uint32(bits.ReverseBytes16(buf[18])) << 16
	m.Float32 = extern.CustomFloat32(math.Float32frombits(tmp32))
	// Float64
	tmp64 = uint64(bits.ReverseBytes16(buf[21])) | uint64(bits.ReverseBytes16(buf[22])) << 16 | uint64(bits.ReverseBytes16(buf[23])) << 32 | uint64(bits.ReverseBytes16(buf[24])) << 48
	m.Float64 = extern.CustomFloat64(math.Float64frombits(tmp64))
	// StringASCII8
	bytes = make([]byte, 18)
	for i, v := range buf[25:34] {
		first := byte(v)
		if first == 0 {bytes = bytes[:i*2];break} // stop on empty char
		bytes[i*2] = first
		second := byte(v >> 8)
		if second == 0 {bytes = bytes[:i*2+1];break} // stop on empty char
		bytes[i*2+1] = second
	}
	m.StringASCII8 = extern.CustomString(bytes)
	// StringASCII16
	bytes = make([]byte, 9)
	for i, v := range buf[34:43] {
		if v == 0 {bytes = bytes[:i];break} // stop on empty char
		bytes[i] = byte(v>>8)
	}
	m.StringASCII16 = extern.CustomString(bytes)
	// StringUTF816
	runes = make([]rune, 9)
	for i, v := range buf[43:52] {
		if v == 0 {runes = runes[:i];break} // stop on empty char
		runes[i] = rune(v >> 8) | rune(v << 8)
	}
	m.StringUTF816 = extern.CustomString(runes)
	// Bool
	tmp16 = bits.ReverseBytes16(buf[52]) & 0x0001
	if tmp16 != 0 { m.Bool = true } else { m.Bool = false }
	// Bit1
	tmp16 = bits.ReverseBytes16(buf[53]) & 0x0002
	if tmp16 != 0 { m.Bit1 = true } else { m.Bit1 = false }
	// Bit3
	tmp16 = bits.ReverseBytes16(buf[53]) & 0x0008
	if tmp16 != 0 { m.Bit3 = true } else { m.Bit3 = false }
	// Bit14
	tmp16 = bits.ReverseBytes16(buf[53]) & 0x4000
	if tmp16 != 0 { m.Bit14 = true } else { m.Bit14 = false }
	// Uint16Array[0]
	m.Uint16Array[0] = extern.CustomUint16(bits.ReverseBytes16(buf[54]))
	// Uint16Array[1]
	m.Uint16Array[1] = extern.CustomUint16(bits.ReverseBytes16(buf[55]))
	// Uint16Array[2]
	m.Uint16Array[2] = extern.CustomUint16(bits.ReverseBytes16(buf[56]))
	// Uint16Array[3]
	m.Uint16Array[3] = extern.CustomUint16(bits.ReverseBytes16(buf[57]))
	// Uint16Array[4]
	m.Uint16Array[4] = extern.CustomUint16(bits.ReverseBytes16(buf[58]))
	// Uint32Array[0]
	m.Uint32Array[0] = extern.CustomUint32(bits.ReverseBytes16(buf[59])) | extern.CustomUint32(bits.ReverseBytes16(buf[60])) << 16
	// Uint32Array[1]
	m.Uint32Array[1] = extern.CustomUint32(bits.ReverseBytes16(buf[63])) | extern.CustomUint32(bits.ReverseBytes16(buf[64])) << 16
	// Uint32Array[2]
	m.Uint32Array[2] = extern.CustomUint32(bits.ReverseBytes16(buf[67])) | extern.CustomUint32(bits.ReverseBytes16(buf[68])) << 16
	// Uint32Array[3]
	m.Uint32Array[3] = extern.CustomUint32(bits.ReverseBytes16(buf[71])) | extern.CustomUint32(bits.ReverseBytes16(buf[72])) << 16
	// Uint32Array[4]
	m.Uint32Array[4] = extern.CustomUint32(bits.ReverseBytes16(buf[75])) | extern.CustomUint32(bits.ReverseBytes16(buf[76])) << 16
	// Float32Array[0]
	tmp32 = uint32(bits.ReverseBytes16(buf[79])) | uint32(bits.ReverseBytes16(buf[80])) << 16
	m.Float32Array[0] = extern.CustomFloat32(math.Float32frombits(tmp32))
	// Float32Array[1]
	tmp32 = uint32(bits.ReverseBytes16(buf[81])) | uint32(bits.ReverseBytes16(buf[82])) << 16
	m.Float32Array[1] = extern.CustomFloat32(math.Float32frombits(tmp32))
	// Float32Array[2]
	tmp32 = uint32(bits.ReverseBytes16(buf[83])) | uint32(bits.ReverseBytes16(buf[84])) << 16
	m.Float32Array[2] = extern.CustomFloat32(math.Float32frombits(tmp32))
	// Float32Array[3]
	tmp32 = uint32(bits.ReverseBytes16(buf[85])) | uint32(bits.ReverseBytes16(buf[86])) << 16
	m.Float32Array[3] = extern.CustomFloat32(math.Float32frombits(tmp32))
	// Float32Array[4]
	tmp32 = uint32(bits.ReverseBytes16(buf[87])) | uint32(bits.ReverseBytes16(buf[88])) << 16
	m.Float32Array[4] = extern.CustomFloat32(math.Float32frombits(tmp32))
	// BoolArray[0]
	tmp16 = bits.ReverseBytes16(buf[89]) & 0x0001
	if tmp16 != 0 { m.BoolArray[0] = true } else { m.BoolArray[0] = false }
	// BoolArray[1]
	tmp16 = bits.ReverseBytes16(buf[90]) & 0x0001
	if tmp16 != 0 { m.BoolArray[1] = true } else { m.BoolArray[1] = false }
	// BoolArray[2]
	tmp16 = bits.ReverseBytes16(buf[91]) & 0x0001
	if tmp16 != 0 { m.BoolArray[2] = true } else { m.BoolArray[2] = false }
	// BoolArray[3]
	tmp16 = bits.ReverseBytes16(buf[92]) & 0x0001
	if tmp16 != 0 { m.BoolArray[3] = true } else { m.BoolArray[3] = false }
	// BoolArray[4]
	tmp16 = bits.ReverseBytes16(buf[93]) & 0x0001
	if tmp16 != 0 { m.BoolArray[4] = true } else { m.BoolArray[4] = false }
	// BitField16
	m.BitField16 = BitField16[CustomUint16](bits.ReverseBytes16(buf[94]))
	// StringASCII32
	bytes = make([]byte, 0, 2)
	for i := 0; i < 2; i++ {
		first := uint16(buf[96+i*2] >> 8) | uint16(buf[96+i*2] << 8)
		second := uint16(buf[96+i*2+1] >> 8) | uint16(buf[96+i*2+1] << 8)
		tmp32 = uint32(first) | uint32(second) << 16
		if tmp32 == 0 {break} // stop on empty char
		bytes = append(bytes, byte(tmp32))
	}
	m.StringASCII32 = extern.CustomString(bytes)
	// StringUTF832
	runes = make([]rune, 0, 2)
	for i := 0; i < 2; i++ {
		first := uint16(buf[100+i*2] >> 8) | uint16(buf[100+i*2] << 8)
		second := uint16(buf[100+i*2+1] >> 8) | uint16(buf[100+i*2+1] << 8)
		tmp32 = uint32(first) | uint32(second) << 16
		if tmp32 == 0 {break} // stop on empty char
		runes = append(runes, rune(tmp32))
	}
	m.StringUTF832 = extern.CustomString(runes)

	return nil
}

