// Code generated by protoreg. DO NOT EDIT.
package tests

func (m StringChar8BigEndian) Marshal() ([]uint16, error) {
	buf := make([]uint16, 2)
	// Value
	length := len(m.Value)
	for i := 0; i < length; i+=2 {
		if i >= 4 {break}
		b1 := m.Value[i]
		var b2 byte
		if i+1 < length {b2 = m.Value[i+1]}
		buf[0+i/2] = uint16(b1) << 8 | uint16(b2)
	}

	return buf, nil
}

func (m *StringChar8BigEndian) Unmarshal(buf []uint16) error {
	var bytes []byte
	// Value
	bytes = make([]byte, 4)
	for i, v := range buf[0:2] {
		first := byte(v >> 8)
		if first == 0 {bytes = bytes[:i*2];break} // stop on empty char
		bytes[i*2] = first
		second := byte(v)
		if second == 0 {bytes = bytes[:i*2+1];break} // stop on empty char
		bytes[i*2+1] = second
	}
	m.Value = string(bytes)

	return nil
}

func (m StringChar8LittleEndian) Marshal() ([]uint16, error) {
	buf := make([]uint16, 2)
	// Value
	length := len(m.Value)
	for i := 0; i < length; i+=2 {
		if i >= 4 {break}
		b1 := m.Value[i]
		var b2 byte
		if i+1 < length {b2 = m.Value[i+1]}
		buf[0+i/2] = uint16(b1) | uint16(b2) << 8
	}

	return buf, nil
}

func (m *StringChar8LittleEndian) Unmarshal(buf []uint16) error {
	var bytes []byte
	// Value
	bytes = make([]byte, 4)
	for i, v := range buf[0:2] {
		first := byte(v)
		if first == 0 {bytes = bytes[:i*2];break} // stop on empty char
		bytes[i*2] = first
		second := byte(v >> 8)
		if second == 0 {bytes = bytes[:i*2+1];break} // stop on empty char
		bytes[i*2+1] = second
	}
	m.Value = string(bytes)

	return nil
}

func (m StringUTF16BigEndian) Marshal() ([]uint16, error) {
	buf := make([]uint16, 5)
	var i int
	// Value
	i = 0
	for _, r := range m.Value {
		if i >= 5 {break}
		buf[0+i] = uint16(r)
		i++
	}

	return buf, nil
}

func (m *StringUTF16BigEndian) Unmarshal(buf []uint16) error {
	var runes []rune
	// Value
	runes = make([]rune, 5)
	for i, v := range buf[0:5] {
		if v == 0 {runes = runes[:i];break} // stop on empty char
		runes[i] = rune(v)
	}
	m.Value = string(runes)

	return nil
}

func (m StringUTF16LittleEndian) Marshal() ([]uint16, error) {
	buf := make([]uint16, 5)
	var i int
	// Value
	i = 0
	for _, r := range m.Value {
		if i >= 5 {break}
		buf[0+i] = uint16(r >> 8) | uint16(r << 8)
		i++
	}

	return buf, nil
}

func (m *StringUTF16LittleEndian) Unmarshal(buf []uint16) error {
	var runes []rune
	// Value
	runes = make([]rune, 5)
	for i, v := range buf[0:5] {
		if v == 0 {runes = runes[:i];break} // stop on empty char
		runes[i] = rune(v >> 8) | rune(v << 8)
	}
	m.Value = string(runes)

	return nil
}

func (m StringUTF32BigHighWord) Marshal() ([]uint16, error) {
	buf := make([]uint16, 4)
	var i int
	var tmp32 uint32
	// Value
	i = 0
	for _, r := range m.Value {
		if i >= 2 {break}
		tmp32 = uint32(r)
		buf[0+i*2] = uint16(tmp32 >> 16)
		buf[0+i*2+1] = uint16(tmp32)
		i++
	}

	return buf, nil
}

func (m *StringUTF32BigHighWord) Unmarshal(buf []uint16) error {
	var runes []rune
	var tmp32 uint32
	// Value
	runes = make([]rune, 0, 2)
	for i := 0; i < 2; i++ {
		first := buf[0+i*2]
		second := buf[0+i*2+1]
		tmp32 = uint32(second) | uint32(first) << 16
		if tmp32 == 0 {break} // stop on empty char
		runes = append(runes, rune(tmp32))
	}
	m.Value = string(runes)

	return nil
}

func (m StringUTF32LittleLowWord) Marshal() ([]uint16, error) {
	buf := make([]uint16, 4)
	var i int
	var tmp32 uint32
	// Value
	i = 0
	for _, r := range m.Value {
		if i >= 2 {break}
		tmp32 = uint32(r)
		buf[0+i*2] = uint16(tmp32)>>8 | uint16(tmp32)<<8
		buf[0+i*2+1] = uint16(tmp32>>16)>>8 | uint16(tmp32>>16)<<8
		i++
	}

	return buf, nil
}

func (m *StringUTF32LittleLowWord) Unmarshal(buf []uint16) error {
	var runes []rune
	var tmp32 uint32
	// Value
	runes = make([]rune, 0, 2)
	for i := 0; i < 2; i++ {
		first := uint16(buf[0+i*2] >> 8) | uint16(buf[0+i*2] << 8)
		second := uint16(buf[0+i*2+1] >> 8) | uint16(buf[0+i*2+1] << 8)
		tmp32 = uint32(first) | uint32(second) << 16
		if tmp32 == 0 {break} // stop on empty char
		runes = append(runes, rune(tmp32))
	}
	m.Value = string(runes)

	return nil
}

